### ISSUE TITLE
Update Readme with usage example

### ISSUE THREAD

**Issue by curtpm** [NVIDIA/libnvidia-container#1]
it would be nice to have an example (maybe docker) run command to demonstrate how to use this.

**Comment by 3XX0** [comment]
Yes, documentation, packaging and samples are coming.
Having said that, this library is not designed to be used directly by users but rather should be integrated in the container runtime. For example, nvidia-docker will leverage it in 2.0.

**Comment by dwjp** [comment]
@3XX0 Could you please clarify a little more how this is intended to be used?

From my understanding:
* Container runtime (Docker, Singularity) would use this, and expose to user with arguments that select host GPU and driver?
* No need for anything on container aside from application and CUDA?

**Comment by 3XX0** [comment]
@dwjp That's right! We're working on Docker right now so NVIDIA Docker will be the first to support it, but we plan to enable other runtimes as well in the future (e.g. CRI, LXD, Systemd, RKT).

Regarding Singularity, it's still unclear. We proposed some patches already but they didn't want to depend on an external library. Instead, they are trying to hack it with some shell scripts.

**Comment by 3XX0** [comment]
I just updated the README with a simple example using the new CLI.
BTW, Singularity will probably leverage it as some point too.
