### ISSUE TITLE
why not update the cgroup file through the update interface of dockerd?

### ISSUE THREAD

**Issue by ruster-cn** [NVIDIA/libnvidia-container#101]
When libnvidia-container mounts gpu driver-related libraries and devices, why not update the cgroup file through the update interface of dockerd? 
If it is updated through the update interface of dockerd, is it not guaranteed that the state of the container in the docker engine is consistent with the real state of the container?

**Comment by ruster-cn** [comment]
@klueska can you help me？

**Comment by elezar** [comment]
@ruster-cn the NVIDIA Container Library and the associated CLI are intended to be container engine agnostic. As such we cannot rely on docker functionality being present to make changes.

We are in the process of reworking how the NVIDIA container stack functions under certain conditions and these may address the issue with an inconsistent container state. I hope this answers your question.

I am closing this issue. Please reopen if you do not feel that your question was sufficiently answered.
