### ISSUE TITLE
nvidia-container-cli: initialization error: cuda error: unknown error

### ISSUE THREAD

**Issue by qingshanyinyin** [NVIDIA/libnvidia-container#103]
I have encountered the similar problem as @JerrettLevensalor, the error is <initialization error: cuda error: unknown error\\n\""": unknown>> !
![image](https://user-images.githubusercontent.com/35218255/91153815-4bb7ce80-e6f3-11ea-8eb8-0c39995814b2.png)

I have read some code of the libnvidia-container, and i think the problem must be in libnvidia-container ! 
How can i solve the problem?
Thanks!

**Comment by klueska** [comment]
Usually this points to a driver installation error. That said, what version of libnvidia-container are you using? The CUDA dependance was removed in 1.1.0.

**Comment by qingshanyinyin** [comment]
They have restarted the computer, and solved it ! It happens ocasionally, so i want to know why? The problem is that I can not recure the problem! The libnvidia-container is v1.0.2！

**Comment by qingshanyinyin** [comment]
They have restarted the computer, and solved it ! It happens ocasionally, so i want to know why? The problem is that I can not recure the problem! The libnvidia-container is v1.0.2！@klueska

**Comment by qingshanyinyin** [comment]
![image](https://user-images.githubusercontent.com/35218255/91308412-d4ad3380-e7e1-11ea-98b4-1bf45282346e.png)
fig.1 call_cuda(driver.c)
![image](https://user-images.githubusercontent.com/35218255/91308619-22c23700-e7e2-11ea-98b4-beffddff55b3.png)
fig2 driver_init(driver.c)
Is this error in the function driver_init_1 (fig.2) which base on GPU driver ?  I  can not find the definition of the function ！And i want to know whether it calls the call_cuda(fig.1)!  Thanks!

**Comment by klueska** [comment]
That function is generated by `rpcgen`, which ultimately calls `driver_init_1_svc` under the hood. In version 1.0.2 (which you indicated you are using) the `driver_init_1_svc` used make the following call:

```
        if (call_cuda(ctx, cuInit, 0) < 0)
                goto fail;
```

This is no longer done in newer versions of `libnvidia-container`.

However, if this call were to fail in the past, you would see the error you are getting. As I mentioned before, this is something out of control of `libnvidia-container` and points to a problem with the underlying driver.

**Comment by qingshanyinyin** [comment]
I got it ! Think u very much! @klueska
