### ISSUE TITLE
libnvidia-container1 is not installing

### ISSUE THREAD

**Issue by ktsantana** [NVIDIA/libnvidia-container#106]
Hi, I'm trying to install libnvidia-container1 package on CentOS 7.8 x86_64. But when I start, is unable to install:

1) Command
=> yum install libnvidia-container1
Resolving Dependencies
--> Running transaction check
---> Package libnvidia-container1.x86_64 0:1.2.0-1 will be installed
--> Finished Dependency Resolution

>>> Dependencies Resolved
===========================================================================================================================================================================
 Package                                         Arch                              Version                            Repository                                      Size
===========================================================================================================================================================================
>>> Installing:
 libnvidia-container1                            x86_64                            1.2.0-1                            libnvidia-container                             83 k

>>> Transaction Summary
===========================================================================================================================================================================
Install  1 Package

Total size: 83 k
Installed size: 225 k
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7/libnvidia-container/packages/libnvidia-container1-1.2.0-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID ac1160cd: NOKEY
Retrieving key from https://nvidia.github.io/libnvidia-container/gpgkey

The GPG keys listed for the "libnvidia-container" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

Failing package is: libnvidia-container1-1.2.0-1.x86_64
GPG Keys are configured as: https://nvidia.github.io/libnvidia-container/gpgkey

2) Config (/etc/yum.repos.d/nvidia.repo)
[libnvidia-container]
name=libnvidia-container
#baseurl=https://nvidia.github.io/libnvidia-container/stable/centos7/$basearch
baseurl=https://nvidia.github.io/libnvidia-container/stable/centos7/x86_64
repo_gpgcheck=1
gpgcheck=1
enabled=1
gpgkey=https://nvidia.github.io/libnvidia-container/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt

3) gpg-pubkey-f796ecb0-59cd5831 >>> Packager    : NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>

I tried to install by Spacewalk respository too, but I get the same error.

What I'm doing wrong, May you help me?

**Comment by klueska** [comment]
Looks like you need to update your keys. Follow the instructions for updating your keys at the bottom of this:
https://nvidia.github.io/libnvidia-container/

**Comment by elezar** [comment]
@ktsantana is this still an issue? Since the keys have since been rotated, I'm closing this. Please reopen if this is still a problem.
