### ISSUE TITLE
Could neither run `yum update` nor `yum makecache` with the `libnvidia-container` repo enabled

### ISSUE THREAD

**Issue by xuhdev** [NVIDIA/libnvidia-container#108]
For both `yum update` and `yum makecache` (when following the key update procedure outlined at https://nvidia.github.io/libnvidia-container/ ), I got the following error:

> https://nvidia.github.io/libnvidia-container/centos7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be 
verified for libnvidia-container
> Trying other mirror.

I'm on CentOS 7.

**Comment by klueska** [comment]
The old gpg key recently expired and we had to update it to a new expiration date.
Can you try reimporting the gpg key (as per the instructions on https://nvidia.github.io/libnvidia-container/):
```
DIST=$(sed -n 's/releasever=//p' /etc/yum.conf)
DIST=${DIST:-$(. /etc/os-release; echo $VERSION_ID)}
sudo rpm -e gpg-pubkey-f796ecb0
sudo gpg --homedir /var/lib/yum/repos/$(uname -m)/$DIST/libnvidia-container/gpgdir --delete-key f796ecb0
sudo yum makecache
```

**Comment by xuhdev** [comment]
I've already followed the procedure (as mentioned in the original report):

```
$ DIST=$(sed -n 's/releasever=//p' /etc/yum.conf)                                                                        
$ DIST=${DIST:-$(. /etc/os-release; echo $VERSION_ID)}                                                                   
$ sudo rpm -e gpg-pubkey-f796ecb0                                                                                        
error: package gpg-pubkey-f796ecb0 is not installed                                                                           
$ sudo gpg --homedir /var/lib/yum/repos/$(uname -m)/$DIST/libnvidia-container/gpgdir --delete-key f796ecb0               
gpg (GnuPG) 2.0.22; Copyright (C) 2013 Free Software Foundation, Inc.                                                         
This is free software: you are free to change and redistribute it.                                                            
There is NO WARRANTY, to the extent permitted by law.                                                                         
                                                                                                                              
gpg: keyblock resource `/var/lib/yum/repos/x86_64/7.8/libnvidia-container/gpgdir/secring.gpg': No such file or directory      
gpg: keyblock resource `/var/lib/yum/repos/x86_64/7.8/libnvidia-container/gpgdir/pubring.gpg': No such file or directory      
gpg: key "f796ecb0" not found: Unknown system error                                                                           
gpg: f796ecb0: delete key failed: Unknown system error                                                                        
$ sudo yum makecache
# Here the error message of the original report...
```

**Comment by klueska** [comment]
That's odd. The key should be automatically imported when you re-run `yum makecache`.
Can you show me the output of:
```
cat /etc/yum.repos.d/libnvidia-container.repo
```

There should be the following line in there:
```
gpgkey=https://nvidia.github.io/libnvidia-container/gpgkey
```

If it's there, then something in your settings is preventing this from being downloaded / installed.

**Comment by xuhdev** [comment]
I figured out the issue. The gpg homedir is not `/var/lib/yum/repos/$(uname -m)/$DIST/libnvidia-container/gpgdir`. `$DIST` is `7.8`, but in the actually path, the string `7Workstation` is at where `$DIST` is. Maybe `$DIST` is not computed correctly?

**Comment by elezar** [comment]
@xuhdev it seems as if you were able to resolve the error that you were seeing. I am closing this issue but please feel free to reopen if you're still having problems.
