### ISSUE TITLE
Was there a signature change

### ISSUE THREAD

**Issue by samikama** [NVIDIA/libnvidia-container#109]
Package mangers report invalid signatures on the repositories. Was there an unannounced signature change recently? Would it be possible to revert back to old signature since this will require manual interventions on the hosts relying on your repositories.

Thanks

**Comment by klueska** [comment]
The key wasn't changed, but it did expire on 2020-09-17.
```
Warning: apt-key output should not be parsed (stdout is not a terminal)
          C95B 321B 61E8 8C18 09C4  F759 DDCA E044 F796 ECB0
    uid           [ unknown] NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>
    sub   rsa2048 2019-09-18 [S] [expires: 2020-09-17]
```

This happens periodically, requiring the key to be refreshed, as shown in the instructions at the bottom of:
https://nvidia.github.io/libnvidia-container/

The latest key expires on 2021-06-16.
```
$ apt-key list | grep NVIDIA -A 1 -B 1
Warning: apt-key output should not be parsed (stdout is not a terminal)
      C95B 321B 61E8 8C18 09C4  F759 DDCA E044 F796 ECB0
uid           [ unknown] NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>
sub   rsa2048 2019-09-18 [S] [expires: 2021-06-16]
```
