### ISSUE TITLE
CentOS 7 files unavailable

### ISSUE THREAD

**Issue by ebryerwork** [NVIDIA/libnvidia-container#110]
I'm unable to access files for CentOS 7, e.g.. `lynx https://nvidia.github.io/libnvidia-container/centos7/` returns a 404 error followed by this text:

`# Unsupported distribution! # Check https://nvidia.github.io/libnvidia-container`

Using the full path to the xml file results in the same error.

**Comment by klueska** [comment]
This is expected because there is no index.html file at that URL (so you are getting the standard 404 error back).

The files are there though -- they follow the paths relative to:
https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/

**Comment by ebryerwork** [comment]
Thanks. I am closing this issue.
