### ISSUE TITLE
wrong libnvidia-container.list content

### ISSUE THREAD

**Issue by pedrombmachado** [NVIDIA/libnvidia-container#112]
Dear Nvidia team,
  Please check the content of the https://nvidia.github.io/libnvidia-container/ubuntu20.04/libnvidia-container.list because it is pointing to the 18.04.
See below
>deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
>#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /

**Comment by klueska** [comment]
This is expected. Under the hood the 20.04 directory is just a symlink to 18.04.
See: https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable
