### ISSUE TITLE
https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/x86_64 not available

### ISSUE THREAD

**Issue by pedrombmachado** [NVIDIA/libnvidia-container#113]
Dear Nvidia team,
  Both the following links aren't available:
https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/x86_64
https://nvidia.github.io/libnvidia-container/stable/ubuntu20.04/x86_64

**Comment by klueska** [comment]
The correct path is with `amd64` on the end (not x86_64).

That said, there are no `index.html` files under those folders (so you will get a 404 if you try to access just the directory). 

But if you try and pull a specific file from underneath those paths, you should be able to access them.

For example:
```
wget https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64/libnvidia-container-dev_1.3.0-1_amd64.deb
wget https://nvidia.github.io/libnvidia-container/stable/ubuntu20.04/amd64/libnvidia-container-dev_1.3.0-1_amd64.deb
```

**Comment by xkszltl** [comment]
```
< HTTP/2 404 
< server: GitHub.com
< content-type: text/html; charset=utf-8
< access-control-allow-origin: *
< etag: "5fd87ad6-51"
< x-proxy-cache: MISS
< x-github-request-id: E0FE:5C1D:899F28:A78524:5FD90D85
< accept-ranges: bytes
< date: Tue, 15 Dec 2020 19:24:59 GMT
< via: 1.1 varnish
< age: 6
< x-served-by: cache-tyo19928-TYO
< x-cache: HIT
< x-cache-hits: 1
< x-timer: S1608060300.766835,VS0,VE0
< vary: Accept-Encoding
< x-fastly-request-id: e841ede3982bd9a77779a49c67534f3151b3f2cf
< content-length: 81
< 
# Unsupported distribution!
# Check https://nvidia.github.io/libnvidia-container
* Connection #0 to host nvidia.github.io left intact
* Closing connection 0
```

"Unsupported distribution!" may not be a good message for 404 in this case.

**Comment by klueska** [comment]
Yes, of course. It's just not been a high priority to fix this unfortunately :/
