### ISSUE TITLE
RHEL Support

### ISSUE THREAD

**Issue by ebryerwork** [NVIDIA/libnvidia-container#114]
Have you dropped all support for RHEL systems? I can't find any files for them.

Erik Bryer
ebryer@isi.edu

**Comment by klueska** [comment]
The support matrix is here:
https://nvidia.github.io/libnvidia-container/

Where are you looking for files for them that you can't find?

Stable packages can be seen here:
https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable

And then accessed through nvidia.github.io/libnvidia-container

**Comment by ebryerwork** [comment]
The yum repo, nvidia-container-runtime.repo, is looking for them here: https://nvidia.github.io/libnvidia-container/centos7/$basearch where $basearch=x86_64. I get the message: 
# Unsupported distribution! # Check https://nvidia.github.io/libnvidia-container. 
This next might be irrelevant, but if I go to https://nvidia.github.io/libnvidia-container/ubuntu20.04/libnvidia-container.list
I get a text file, but https://nvidia.github.io/libnvidia-container/centos7/libnvidia-container.list gives the same error message I mentioned above.

**Comment by klueska** [comment]
This is expected (though admittedly not inutitive) because there is no `index.html` file at that URL (so you are getting the standard 404 error back).

The files are there though -- they follow the paths relative to:
https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/

**Comment by ebryerwork** [comment]
Thanks. I am closing this issue.
