### ISSUE TITLE
Wrong cgroup root path detected 

### ISSUE THREAD

**Issue by Asakuri** [NVIDIA/libnvidia-container#119]
When kubelet's cgroup driver is configured to systemd, containerd will use the format "slice:prefix:name" as the cgroup path (kubepods-pod80540e95304d8cece2ae2afafd8b8976.slice:cri-containerd:xxxx for example)
https://github.com/containerd/containerd/blob/master/pkg/cri/server/helpers_linux.go#L70
but when nvidia container prestart hook tries to detect cgroup path, it trims the suffix after ":", which will result to the "no such file" error when mounting binaries/libraries.

containerd[76114]: time="2020-12-04T08:52:13.029072066Z" level=error msg="StartContainer for \"7a1453c6e7ab8af7395ccc8dac5efcffa94a0834aa7b252e1dcd5b51f92bf13e\" failed" error="failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: open failed: /sys/fs/cgroup/devices/system.slice/containerd.service/kubepods-pod80540e95304d8cece2ae2afafd8b8976.slice/devices.allow: no such file or directory: unknown"

https://github.com/NVIDIA/libnvidia-container/blob/31674b94873c5e21a9900bfcd660edb315739e7d/src/nvc_container.c#L90

According to [this man page](https://man7.org/linux/man-pages/man7/cgroups.7.html)

>  For each cgroup hierarchy of which the process is a member, 
    there is one entry containing three colon-separated fields:
                  **hierarchy-ID:controller-list:cgroup-path**

So I think when extracting the cgroup path, we don't need to trim the suffix after the third colon

**Comment by klueska** [comment]
I am able to reproduce this error and will look into it soon.
Thanks for reporting.

**Comment by diyi0926** [comment]
I'm facing the same error, may I know when will you plan to fix this? Thanks! @klueska

**Comment by klueska** [comment]
This will be fixed in the 1.4.0 release of libnvidia-container, coming out in January.

**Comment by diyi0926** [comment]
Do you have a specific time for the January release now? Thanks @klueska

**Comment by klueska** [comment]
The fix for this has now been merged and will be included in a patch release of `libnvidia-container` coming next week.
https://gitlab.com/nvidia/container-toolkit/libnvidia-container/-/merge_requests/49
