### ISSUE TITLE
Build Issues on Amazon Linux AMIs

### ISSUE THREAD

**Issue by vinayan3** [NVIDIA/libnvidia-container#12]
I'm trying to build on Amazon Linux AMIs because if I install it via RPM it has issues running. 
```
 /usr/lib64/libnvidia-container.so.1: undefined symbol: cap_get_bound
```

I tried to compile to overcome this issue. I ran into another problem.
```
In file included from /usr/include/sys/prctl.h:22:0,
                 from /home/ec2-user/libnvidia-container/src/nvc_ldcache.c:10:
/usr/include/linux/prctl.h:134:2: error: unknown type name ‘__u64’
  __u64 start_code;  /* code section bounds */
  ^
/usr/include/linux/prctl.h:135:2: error: unknown type
```

I've installed the kernel headers which I thought would provide `__u64`. Any help or support for this compiling on Amazon Linux?

**Comment by 3XX0** [comment]
What version of `libcap` is installed on your Amazon Linux AMI?
Also can you give me the output of:

* `echo '#include <linux/types.h>' | gcc -E - | grep __u64 `
* `echo '#include <sys/prctl.h>' | gcc -E - | grep __u64 `

**Comment by vinayan3** [comment]
The Linux AMI version is `4.9.62-21.56.amzn1.x86_64`. It was built in September.
# Libcap
Version of `libcap` is at 2.16:
```
[ec2-user]# ldconfig -v | grep libcap
	libcap-ng.so.0 -> libcap-ng.so.0.0.0
	libcap.so.2 -> libcap.so.2.16

[ec2-user]# yum search --show-duplicates libcap
devel-2.16-5.5.8.amzn1.x86_64 : Development files for libcap
libcap-2.16-5.5.8.amzn1.x86_64 : Library for getting and setting POSIX.1e capabilities
libcap-ng-0.7.5-4.15.amzn1.i686 : An alternate posix capabilities library
```
# Header Information
* `echo '#include <linux/types.h>' | gcc -E - | grep __u64`
```
[ec2-user]# echo '#include <linux/types.h>' | gcc -E - | grep __u64
__extension__ typedef unsigned long long __u64;
typedef __u64 __le64;
typedef __u64 __be64;
```
* `echo '#include <sys/prctl.h>' | gcc -E - | grep __u64`
```
[ec2-user]# echo '#include <sys/prctl.h>' | gcc -E - | grep __u64
__extension__ typedef unsigned long long __u64;
typedef __u64 __le64;
typedef __u64 __be64;
 __u64 start_code;
 __u64 end_code;
 __u64 start_data;
 __u64 end_data;
 __u64 start_brk;
 __u64 brk;
 __u64 start_stack;
 __u64 arg_start;
 __u64 arg_end;
 __u64 env_start;
 __u64 env_end;
 __u64 *auxv;
```

**Comment by 3XX0** [comment]
Closing since this configuration is not officially supported and [Amazon Linux 2 LTS](https://aws.amazon.com/amazon-linux-2/) fixed these issues anyway.

**Comment by mzsanford** [comment]
As noted in https://github.com/NVIDIA/nvidia-docker/issues/553 this affects the latest [Amazon ECS Optimized AMIs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html). What about this configuration is not officially supported? The versions, or just the Amazon Linux part of it? I was unable to find any reference in the repo on what was/was not officially supported.

**Comment by 3XX0** [comment]
@mzsanford This should fix the issue.
We will probably release packages as well for the next release of nvidia-docker.
