### ISSUE TITLE
How to add or delete the GPUs in the container after the container is created?

### ISSUE THREAD

**Issue by qingshanyinyin** [NVIDIA/libnvidia-container#123]
As we know the nvidia-docker use -e=0,1,2 (or -gpus=...) to add GPUs into the container to use! 
At first, i add 0,1,2 GPUs into the container. when i done some work, the 2th (index=2) GPU is no need to use. So, i want to release the 2th GPU (do not kill the container) to annother user! 
As before, annother scenario is to add one more GPU to the  runnig container which (0,1,2th)  GPUs is not enough to use! 
Is there some ways to achieve it  in nvidia-docker ? Thanks!

**Comment by klueska** [comment]
Just to make sure I understand you. orrectly. You are asking 2 questions:

1) How to remove a GPU from a running container after it has been started.
2) How to add a GPU to a running container after it has been started.

For (1), it's unlear exactlxy what you mean by "release" the GPU. Nothing in `libnvidia-container` puts a lock on a GPU. You are free to inject the same GPU into multiple containers without restriction. Your applications would just need to be disciplined enough to coordinate and make sure they weren't using the same GPU at the same time.

For (2), this is not technically supported by `libnvidia-container`. You could probably hack something together to make it work, but I wouldn't recommend it.

**Comment by qingshanyinyin** [comment]
Thank u very much!
 If i can not achive it by this way, could i add or delete the GPUs dynamic in the pod of k8s which has only one container in it and is running?

**Comment by klueska** [comment]
This goes against the K8s resource model. Once a resource is given to a pod it owns that resource for the lifetime of the pod.

**Comment by qingshanyinyin** [comment]
Thanks! I will try it for some special scenario!

**Comment by thundergolfer** [comment]
@qingshanyinyin did you get (2) working? 

> How to add a GPU to a running container after it has been started.
