### ISSUE TITLE
Broken Debian/Ubuntu repositories

### ISSUE THREAD

**Issue by mestia** [NVIDIA/libnvidia-container#133]
Thank you for providing nvidia-container Debian packages.
However by following the instructions on the official site I am not able to fetch the list of packages.
By navigating to: https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/  I get `# Unsupported distribution! # Check https://nvidia.github.io/libnvidia-container`

**Comment by klueska** [comment]
There is no listing available from the webssrver. That is the standard 404 message. If you really need to see what is available you can look directly in the gh-pages branch of the repo:
https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable/ubuntu18.04
