### ISSUE TITLE
Nvidia driver fails to enumerate GPUs with vkEnumeratePhysicalDevices in containers with only a subset of available GPUs

### ISSUE THREAD

**Issue by morphis** [NVIDIA/libnvidia-container#134]
We're using LXD which internally uses libnvidia-container to attach GPUs to system containers it runs. On systems with multiple GPUs we only attach a single GPU to each container we run. When doing that the Nvidia Vulkan driver always fails when calling `vkEnumeratePhysicalDevices` with error `VK_ERROR_INITIALIZATION_FAILED`. This prevents our Vulkan based graphics application to allocate a `VkPhysicalDevice` to use for rendering. As soon as we attach all GPUs available on the system to the container calling `vkEnumeratePhysicalDevices` succeeds again and lists all available GPUs.

It feels a bit like `vkEnumeratePhysicalDevices` is still getting the information from somewhere that the system has multiple GPUs and is then failing because it cannot find the ones not exposed to the LXD container. When running the application using Vulkan with strace you can see the driver is trying to access unavailable `/dev/nvidia<n>` device nodes.

As I am unsure if this is a libnvidia-container or Vulkan driver bug I though it's good first step to start here and then see where to get this best reported.

Thanks!

**Comment by klueska** [comment]
We've taken a look at this internally and concluded the following:

> This is not a container bug – but rather a driver issue with Vulkan/EGL that was fixed very recently.
>
> The upcoming R450 datacenter driver (to be posted on 4/19) _should_ have a fix for it. We missed the cutoff for the R460 datacenter driver release, but this fix should be in the next R460 datacenter driver release in July.

**Comment by morphis** [comment]
@klueska Many thanks for the update!
