### ISSUE TITLE
1.4.0 fails on Debian

### ISSUE THREAD

**Issue by ich777** [NVIDIA/libnvidia-container#136]
Tried to build v1.4.0 on Debian but I get two errors

```
bmake[2]: "/libnvidia-container/deps/src/elftoolchain-0.7.1/mk/elftoolchain.inc.mk" line 12: Could not find bsd.own.mk
bmake[2]: "/libnvidia-container/deps/src/elftoolchain-0.7.1/mk/elftoolchain.inc.mk" line 35: Could not find bsd.inc.mk
```

@klueska is there something I am missing?

**Comment by klueska** [comment]
Are you building with ‚make debian10‘?

**Comment by ich777** [comment]
No, I'm building it natively on my Debian dev machine like always, I think make debian10 is the Docker build process or am I wrong?

**Comment by ich777** [comment]
@klueska I'm building with `DESTDIR=/build/libnvidia-container make install prefix=/usr`

**Comment by klueska** [comment]
Shouldn’t be. There was one change to the build process, but it should have only affected docker builds. There are no new dependencies.

**Comment by klueska** [comment]
Sounds good. This was the only commit that touched the build process: https://github.com/NVIDIA/libnvidia-container/commit/4364a9bac93e924c423b465e62d2a07473f0efbc

**Comment by ich777** [comment]
@klueska investigated a little further and there was actually a problem with bmake on my system but now I got a new error:

```
groff: can't find 'DESC' file
groff: fatal error: invalid device 'ascii'
--- elf_cntl.cat3 ---
groff: can't find 'DESC' file
--- elf.cat3 ---
groff: can't find 'DESC' file
groff: fatal error: invalid device 'ascii'
--- elf_cntl.cat3 ---
groff: fatal error: invalid device 'ascii'
--- elf.cat3 ---
*** [elf.cat3] Error code 1
```

Attached also the full build log that is working just fine from 1.3.3 
[1.3.3-build.log](https://github.com/NVIDIA/libnvidia-container/files/6370252/1.3.3-build.log)

and also

**Comment by fuomag9** [comment]
I'm getting the same error with building main with ubuntu 21.04 by doing a simple `make install`

**Comment by elezar** [comment]
When I modify my `BMAKE` command in `mk/common.mk` to include the `-d -A` flags this shows:
```
.MAKE.MAKEFILES  = /usr/share/mk/sys.mk Makefile /tmp/libnvidia-container/deps/src/elftoolchain-0.7.1/libelf/../mk/elftoolchain.lib.mk /tmp/libnvidia-container/deps/src/elftoolchain-0.7.1/libelf/../mk/elftoolchain.os.mk /tmp/libnvidia-container/deps/src/elftoolchain-0.7.1/libelf/../mk/os.Linux.mk /usr/share/mk/bsd.lib.mk /usr/share/mk/bsd.own.mk /usr/share/mk/bsd.obj.mk /usr/share/mk/bsd.depall.mk /usr/share/mk/bsd.man.mk /usr/share/mk/bsd.nls.mk /usr/share/mk/bsd.files.mk /usr/share/mk/bsd.inc.mk /usr/share/mk/bsd.links.mk /usr/share/mk/bsd.dep.mk /usr/share/mk/bsd.sys.mk /tmp/libnvidia-container/deps/src/elftoolchain-0.7.1/libelf/../mk/elftoolchain.m4.mk /tmp/libnvidia-container/deps/src/elftoolchain-0.7.1/libelf/../mk/elftoolchain.test.mk
```
This shows that (at least in the docker container where we build our binaries) the `/usr/share/mk` files are being include. Are these files present on your system?

**Comment by fuomag9** [comment]
> When I modify my `BMAKE` command in `mk/common.mk` to include the `-d -A` flags this shows:
> 
> ```
> 
> .MAKE.MAKEFILES  = /usr/share/mk/sys.mk Makefile /tmp/libnvidia-container/deps/src/elftoolchain-0.7.1/libelf/../mk/elftoolchain.lib.mk /tmp/libnvidia-container/deps/src/elftoolchain-0.7.1/libelf/../mk/elftoolchain.os.mk /tmp/libnvidia-container/deps/src/elftoolchain-0.7.1/libelf/../mk/os.Linux.mk /usr/share/mk/bsd.lib.mk /usr/share/mk/bsd.own.mk /usr/share/mk/bsd.obj.mk /usr/share/mk/bsd.depall.mk /usr/share/mk/bsd.man.mk /usr/share/mk/bsd.nls.mk /usr/share/mk/bsd.files.mk /usr/share/mk/bsd.inc.mk /usr/share/mk/bsd.links.mk /usr/share/mk/bsd.dep.mk /usr/share/mk/bsd.sys.mk /tmp/libnvidia-container/deps/src/elftoolchain-0.7.1/libelf/../mk/elftoolchain.m4.mk /tmp/libnvidia-container/deps/src/elftoolchain-0.7.1/libelf/../mk/elftoolchain.test.mk
> 
> ```
> 
> This shows that (at least in the docker container where we build our binaries) the `/usr/share/mk` files are being include. Are these files present on your system?

Unfortunately not all of them are present on my system, am I missing some kind of dependency?
`ls /usr/share/mk/
autoconf.mk         install-mk       own.mk
auto.dep.mk         install-new.mk   prlist.mk
autodep.mk          java.mk          prog.mk
auto.obj.mk         ldorder.mk       progs.mk
ChangeLog           lib.mk           README
compiler.mk         libnames.mk      rst2htm.mk
cython.mk           libs.mk          scripts.mk
dep.mk              links.mk         srctop.mk
dirdeps.mk          manifest.mk      stage-install.sh
dirdeps-options.mk  man.mk           subdir.mk
dirdeps-targets.mk  meta2deps.py     sys
doc.mk              meta2deps.sh     sys.clean-env.mk
dpadd.mk            meta.autodep.mk  sys.debug.mk
FILES               meta.stage.mk    sys.dependfile.mk
files.mk            meta.subdir.mk   sys.mk
final.mk            meta.sys.mk      sys.vars.mk
gendirdeps.mk       mk-files.txt     target-flags.mk
host.libnames.mk    mkopt.sh         warnings.mk
host-target.mk      nls.mk           whats.mk
inc.mk              obj.mk           yacc.mk
init.mk             options.mk`

**Comment by elezar** [comment]
These are the dependency that we install in the build container: https://github.com/NVIDIA/libnvidia-container/blob/master/mk/Dockerfile.ubuntu#L6-L23 could it be that one of them are missing?

**Comment by fuomag9** [comment]
> These are the dependency that we install in the build container: https://github.com/NVIDIA/libnvidia-container/blob/master/mk/Dockerfile.ubuntu#L6-L23 could it be that one of them are missing?

Unfortunately even after installing all of them I still get the same error

**Comment by ich777** [comment]
@fuomag9 & @elezar already posted a workaround here:
https://github.com/NVIDIA/libnvidia-container/issues/116#issuecomment-826146121
