### ISSUE TITLE
Following directions for Ubuntu 20.04 gives Ubuntu 18.04 repository list

### ISSUE THREAD

**Issue by AJRepo** [NVIDIA/libnvidia-container#141]
On this page: https://nvidia.github.io/nvidia-docker/

It states run the following commands 

```
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
```

However when you download the file (on Ubuntu 20.04) as in 

`wget https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list`

the file is as follows

```
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
```

which seems wrong to me. I'd think it should be ubuntu20.04 instead of 18.04

Also can you specify - are these commands to be run on the host server or on the container?

**Comment by elezar** [comment]
The 20.04 packages are (currently) the same as the 18.04 releases and the content of the list file are as expected.

The `nvidia-docker` components need to be installed on the host system to be able to launch containers with GPU support. These components are not required in a container that is GPU-enabled.

**Comment by AJRepo** [comment]
Thanks. Closing.
