### ISSUE TITLE
Why is 'COPYING' listed as GPL3?

### ISSUE THREAD

**Issue by Lexmark-chad** [NVIDIA/libnvidia-container#145]
The elfutils project homepage specifically says:

"License. The libraries and backends are dual GPLv2+/LGPLv3+. The utilities are GPLv3+."

The recipe for elfutils in poky/meta/recipes-devtools/elfutils has:

LICENSE_libelf = "GPLv2 | LGPLv3+"

If libnvidia-container just needs to link to libelf then why does the licensing include GPL3?

**Comment by rpavlik** [comment]
LGPL 3 is a set of additional terms that modify GPL 3. So, for an LGPL 3 project, you'll see both a copying and copying.lesser file, this is normal (if somewhat confusing). An explanation like this might be useful to put in the docs if the project is entirely LGPL.

**Comment by klueska** [comment]
I am not a legal expert, but I do know that `libnvidia-container` doesn't just link to a system installed `libelf` library. It downloads the source for `libelf`, patches its `native-elf-format` script for determining the host architecture, and then compiles it into `libelf.a` before statically linking it into `libnvidia-container` itself.

**Comment by Lexmark-chad** [comment]
Thanks for the responses @rpavlik and @klueska.  If the source is downloaded, compiled, and statically linked then I understand why it carries the GPL 3 licensing.  That is the default behavior when building.  If you specify LIBELF=yes then the additional terms of copying.lesser applies.  We use that configuration so the licensing is appropriate for our use.
