### ISSUE TITLE
Unable to run toolkit on Debian

### ISSUE THREAD

**Issue by CourchesneA** [NVIDIA/libnvidia-container#148]
with "default-runtime": "nvidia" set, docker is not able to run:
```
$ docker run hello-world
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall clone3: permission denied: unknown.
ERRO[0001] error waiting for container: context canceled 
```
The issue is already discussed here:
https://github.com/containerd/containerd/issues/6203
It seems it was recently fixed but I think the fix was not published for ubuntu 18.04. Would it be possible to backport it ? I am running on a jetson and ubuntu 20 is not yet available.

**Comment by elezar** [comment]
@CourchesneA the 1.6.0 release of the nvidia-container-toolkit package includes the fix for this issue for non-Jetson platforms. We are actively working on getting the Jetson fix released In the coming days.

**Comment by elezar** [comment]
@CourchesneA we have just published `nvidia-container-toolkit=1.7.0~rc.1-1` packages with this fix for Ubuntu18.04 (and Ubuntu20.04) to our experimental repositories.

You mention that this affects "Debian" which distribution is this exactly?

**Comment by CourchesneA** [comment]
It is the default image for Jetson Xavier NX:
https://developer.nvidia.com/embedded/learn/get-started-jetson-xavier-nx-devkit#write
Which seems to be an L4T version of Ubuntu 18.04

```
$ sudo cat /proc/version
Linux version 4.9.253-tegra (buildbrain@mobile-u64-5497-d3000) (gcc version 7.3.1 20180425 [linaro-7.3-2018.05 revision d29120a424ecfbc167ef90065c0eeb7f91977701] (Linaro GCC 7.3-2018.05) ) #1 SMP PREEMPT Mon Jul 26 12:19:28 PDT 2021
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

**Comment by somera** [comment]
> 

Hello-World is running on my system (Jetson Nano).

```
$ sudo cat /proc/version
Linux version 4.9.253-tegra (buildbrain@mobile-u64-5496-d5000) (gcc version 7.3.1 20180425 [linaro-7.3-2018.05 revision d29120a424ecfbc167ef90065c0eeb7f91977701] (Linaro GCC 7.3-2018.05) ) #1 SMP PREEMPT Mon Jul 26 12:13:06 PDT 2021
$ sudo lsb_release -a
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by CourchesneA** [comment]
@somera it seems to be the same error, in the first case you are not using nvidia runtime so you do not encounter the error. As mentionned, I think the fix will be ported to jetson soon

**Comment by elezar** [comment]
@somera which version of the `nvidia-container-toolkit `package is installed on your system? As mentioned, the fix was released in `nvidia-container-toolkit=1.7.0~rc.1-1`.

**Comment by klueska** [comment]
To get access to this version, you need to have our experimental repo configured as described in the first note here:

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit

**Comment by somera** [comment]
> @somera which version of the `nvidia-container-toolkit `package is installed on your system? As mentioned, the fix was released in `nvidia-container-toolkit=1.7.0~rc.1-1`.

This?

```
$ apt show nvidia-container-toolkit
Package: nvidia-container-toolkit
Version: 1.0.1-1
Priority: optional
Section: utils
Maintainer: NVIDIA CORPORATION <cudatools@nvidia.com>
Installed-Size: 1.814 kB
Depends: libnvidia-container-tools (>= 0.1.0), libnvidia-container-tools (<< 2.0.0)
Breaks: nvidia-container-runtime (<< 2.0.0), nvidia-container-runtime-hook
Replaces: nvidia-container-runtime (<< 2.0.0), nvidia-container-runtime-hook
Homepage: https://github.com/NVIDIA/nvidia-container-runtime/wiki
Download-Size: 502 kB
APT-Manual-Installed: yes
APT-Sources: https://repo.download.nvidia.com/jetson/common r32.6/main arm64 Packages
Description: NVIDIA container runtime hook
 Provides a OCI hook to enable GPU support in containers.
```

**Comment by CourchesneA** [comment]
@klueska Thanks for the info. I can confirm the fix on the experimental repo works. Any ETA on when that will be on the main repo ?

**Comment by elezar** [comment]
We don't have a concrete ETA at the moment.

**Comment by jcreek** [comment]
This is a major blocker for me running https://github.com/linuxserver/docker-plex on Ubuntu 20.04.1 LTS with the below docker-compose file. 

```docker-compose
---
version: "2.3"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    runtime: nvidia
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      #- PLEX_CLAIM= #optional
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /home/jcreek/plex:/config
      - /home/jcreek/plex/tv:/tv
      - /home/jcreek/plex/movies:/movies
      - /home/jcreek/plex/music:/music
    restart: unless-stopped
```

**Comment by elezar** [comment]
@jcreek are you able to verify that the `1.7.0-rc.1` addresses the issues that you are seeing?

**Comment by elezar** [comment]
The `1.7.0-rc.1` packages have been promoted to GA (`1.7.0`) and are available from our `stable` repositories.

See https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.7.0

**Comment by elezar** [comment]
@CourchesneA could you close this issue if your problem has been addressed by the `1.7.0` release?

**Comment by somera** [comment]
Will the update be available for Ubuntu 18.04.6 LTS (GNU/Linux 4.9.253-tegra aarch64) too?

Cause at the moment I have the current version installed:

```
$ sudo apt-get install nvidia-container-runtime
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
nvidia-container-runtime ist schon die neueste Version (3.1.0-1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
```

**Comment by elezar** [comment]
@somera please follow the instructions [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) to add the required repos and get access to the packages. They have not yet been included in Jetpack.

**Comment by somera** [comment]
> @somera please follow the instructions [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) to add the required repos and get access to the packages. They have not yet been included in Jetpack.

ok & thx

**Comment by jcreek** [comment]
Following the instructions here got mine going again, thanks all :) https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker

**Comment by somera** [comment]
Works for me too. thx!

**Comment by stephenjamieson** [comment]
Hi, does the jetson nano include this fix yet?

**Comment by somera** [comment]
> https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker

Just uninstall docker and do this: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker
