### ISSUE TITLE
Why do you mount firmware dir in rw mode?

### ISSUE THREAD

**Issue by D1abloRUS** [NVIDIA/libnvidia-container#152]
Hi!

```bash
/dev/mapper/vg0-lv--root on /usr/lib/firmware/nvidia/470.82.01 type ext4 (rw,nosuid,noexec,relatime)
```

**Comment by D1abloRUS** [comment]
https://github.com/NVIDIA/libnvidia-container/commit/a2d05c686b69322762a012e9a05dc12002309640 persistence-mode was disabled.

**Comment by elezar** [comment]
This is related to #147. We need to rework how the firmware is mounted and will address any inconsistencies then.

**Comment by elezar** [comment]
`libnvidia-container-1.8.0-rc.2` is now live with a fix for this behaviour.

Please see [#111 (comment)](https://github.com/NVIDIA/libnvidia-container/issues/111#issuecomment-989024375) for instructions on how to get access to this RC (or wait for the full release).

**Comment by klueska** [comment]
`libnvidia-container-1.8.0` with a fix for this is now GA

Release notes here:
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.8.0
