### ISSUE TITLE
modify mount container nvidia library directory

### ISSUE THREAD

**Issue by zhaoxuat** [NVIDIA/libnvidia-container#153]
I use nvidia-container-runtime-hook to create container, but all nvidia library default mount in "/usr/lib/x86_64-linux-gnu" directory, has any way to change it?

**Comment by klueska** [comment]
Are you asking if there is a way to have all of the bins/libs injected by `libnvidia-container` to be placed in a custom directory, rather than placed the system libs directory? If so, no there is no way to customize this.

**Comment by zhaoxuat** [comment]
yes, thank!
