### ISSUE TITLE
Debian 11 support

### ISSUE THREAD

**Issue by deric** [NVIDIA/libnvidia-container#156]
Would it be possible to add Debian 11 between supported distributions? Debian 9 has [LTS support](https://wiki.debian.org/LTS) till June 30, 2022

**Comment by klueska** [comment]
We will be adding it in the next few weeks once our cgroupv2 support has landed.

**Comment by deric** [comment]
@klueska Cool, thanks Kevin!

**Comment by klueska** [comment]
`libnvidia-container-1.8.0-rc.2` is now live with some minor updates to fix some edge cases around `cgroupv2` support.

Please see https://github.com/NVIDIA/libnvidia-container/issues/111#issuecomment-989024375 for instructions on how to get access to this RC (or wait for the full release at the end of next week).

**Comment by klueska** [comment]
`libnvidia-container-1.8.0` with `cgroupv2` support is now GA

Release notes here:
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.8.0

**Comment by klueska** [comment]
Debian 11 support has now been added such that running the following should now work as expected:
```
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
```
