### ISSUE TITLE
Question about v1.8.0-rc1

### ISSUE THREAD

**Issue by ich777** [NVIDIA/libnvidia-container#157]
Hi,
just a short question for my understanding.
With the release of v1.8.0-rc1 I've noticed that files for `libnvidia-container-go.so` are now added.
For what are those new files because they are about ten times the size of `libnvidia-container.so`, do I have to keep them or is it save to remove them?
Many regards from Austria!

**Comment by klueska** [comment]
At present, it is only used to add support for cgroupv2. If you don’t need cgroupv2 support and want to exclude it from your build (when building from source) just run make with WITH_NVCGO=no.

**Comment by ich777** [comment]
As always thank you for the quick answer @klueska.
Have a great day!
