### ISSUE TITLE
configure.c in src/cli

### ISSUE THREAD

**Issue by mingfengwuye** [NVIDIA/libnvidia-container#16]
I read some part of the code. 
In my understanding, runc created a container, then through prestart hook call this cli tool to configure some parameters for container (mainly defined in configure.c), finally runc run the container.

Am i right ?

**Comment by 3XX0** [comment]
Yes, [nvidia-container-runtime-hook](https://github.com/NVIDIA/nvidia-container-runtime) calls the CLI to configure GPU support for the container.

**Comment by mingfengwuye** [comment]
thank you!
In configure.c, I see many parameters to be configured, are they all necessary? such as namespace and cgroup. Will not the runtime do these work? Mount driver and set visible GPU may be mandatory, others are optional.

**Comment by 3XX0** [comment]
It depends on the runtime. This library is designed to be runtime agnostic and the different options allow a wide range of configurations.
