### ISSUE TITLE
Is repo URL correct for "ubuntu20.04" identifier?

### ISSUE THREAD

**Issue by wdennis** [NVIDIA/libnvidia-container#165]
When I curl the URL `https://nvidia.github.io/libnvidia-container/ubuntu20.04/libnvidia-container.list`, I am getting the following URLs in the resulting .list file:

```
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
```

Is this expected (and working for U20.04), or are the URLs incorrect?

**Comment by elezar** [comment]
This is expected behaviour. The same packages are used on all ubuntu distributions from 18.04.
