### ISSUE TITLE
RPM repo unavailable to clone or browse

### ISSUE THREAD

**Issue by applematt** [NVIDIA/libnvidia-container#167]
Hello!

We operate on a secure network and packages are made available to our systems via a package mirror server. I'm trying to clone the repo with Foreman; it's reporting `repomd.xml` is not found. When attempting to browse the repository at `https://nvidia.github.io/libnvidia-container/stable/centos8/x86_64/`, I receive the error:

```
# Unsupported distribution! # Check https://nvidia.github.io/libnvidia-container 
````

However, when I add the .repo configuration to my lab VM, yum/dnf are able to download and search for packages without incident.

Is there something I should be doing different when browsing the repository and/or trying to clone it?

Thanks!

**Comment by elezar** [comment]
@applematt the URL in question maps to the following folder: https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable/centos8/x86_64 

This folder contains the architecture-specific packages but not the `repomd.xml`. The https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable/centos8/x86_64/repodata folder does.

**Comment by applematt** [comment]
@elezar , thank you!

**Comment by elezar** [comment]
Hi @applematt. The centos8 packages are used regularly by multiple users and many other distributions redirect to these repos. As such I wouldn't expect any issues with the repository.

**Comment by elezar** [comment]
@applematt thinking about this again, does accessing the raw file at https://raw.githubusercontent.com/NVIDIA/libnvidia-container/gh-pages/stable/centos8/x86_64/repodata/repomd.xml work?

**Comment by applematt** [comment]
Hi @elezar - Sorry for the delayed response. Let me try cloning the repository again and see if its fixed now.

**Comment by applematt** [comment]
It seems that did not resolve the issue. I'm still receiving this error from my mirror server:

```
Katello::Errors::PulpError: PLP0000: not well-formed (invalid token): line 15, column 75
```

In looking at the stack trace, python is throwing an exception for the `xml_iterator` which is called by `parse_repomd`.  The raw error from the XML parser is:

```
ParseError: not well-formed (invalid token)
```

I am not sure what's causing it to choke, so I'll keep digging and let you know if I find anything ... just in case anyone else is using Foreman+Katello or Satellite to mirror this repository.

**Comment by applematt** [comment]
> @applematt thinking about this again, does accessing the raw file at https://raw.githubusercontent.com/NVIDIA/libnvidia-container/gh-pages/stable/centos8/x86_64/repodata/repomd.xml work?

Sorry ... I completely misunderstood your request. 🤦 

Yes, I can access that file. I will see if I can parse it manually to identify the exact issue.
