### ISSUE TITLE
libtirpc v1.1.4 fails when compiling with GCC 10

### ISSUE THREAD

**Issue by riccardo32** [NVIDIA/libnvidia-container#168]
libtirpc v1.1.4 has a know bug with compiling with > GCC-10 
https://bugs.gentoo.org/705896

Returns error 
/usr/lib/gcc/x86_64-cros-linux-gnu/10.3.0/../../../../x86_64-cros-linux-gnu/bin/ld: /tmp/git/libnvidia-container/deps/usr/local/lib/libtirpc.a(libtirpc_la-rpc_generic.o):/tmp/git/libnvidia-container/deps/src/libtirpc-1.1.4/src/rpc_com.h:64: multiple definition of `__svc_xports'; 

Updating libtirpc  to v1.2.6 corrects the issue

**Comment by elezar** [comment]
@riccardo32 is there any reason not to update to the latest version (`1.3.2`)? https://sourceforge.net/projects/libtirpc/

**Comment by riccardo32** [comment]
not at all, should be  > 1.2.6.

> @riccardo32 is there any reason not to update to the latest version (`1.3.2`)? https://sourceforge.net/projects/libtirpc/

**Comment by elezar** [comment]
I have created https://gitlab.com/nvidia/container-toolkit/libnvidia-container/-/merge_requests/164 to bump the version.

**Comment by elezar** [comment]
@riccardo32 we have merged the changes to `main`. I'm closing this issue but please reopen if it does not work as expected.

**Comment by riccardo32** [comment]
Great Thanks so much!
