### ISSUE TITLE
some questions about nvidia-docker v2?

### ISSUE THREAD

**Issue by x1022as** [NVIDIA/libnvidia-container#17]
Hi, all, not sure if this is the right place to ask :)

Have been followed nvidia-docker for a long time( since v1),  we  were working on a accelerator framework in docker then, trying to find a common way to use special devices like nvidia gpu in container easily. our work focus on docker damon, so we got a simple scheme according to v1 nvidia-docker.

now that nvidia-docker comes to v2, and it seems to be a totally different thing comparing with v1.  prestart hook nvidia-container-cli did all the works. just wondering if this is the final project, preparing gpu in prestart hook is a good idea, but is it necessary to do this in a new runtime? is it better to do this with a new docker command and standard runc(docker add a new prestart to runtime spec)

ping @flx42 

Thanks

**Comment by flx42** [comment]
Take a look at this issue, it might answer some questions:
https://github.com/NVIDIA/nvidia-container-runtime/issues/1

In short, it's not required to have a separate runtime. If you can use runc + hook then it's easier, e.g. if you use Red Hat's fork of Docker, or if using CRI-O, or if you control the OCI bundle).

**Comment by x1022as** [comment]
Thanks @flx42  it does resolve my doubt. 

is doing this in prestart hook the final project? any chance that you would do this in another way in the future?

**Comment by flx42** [comment]
Not necessarily, we might integrate into `containerd` in the future.
But libnvidia-container is here to stay, as the basic building block.

Closing for now :)
