### ISSUE TITLE
failed to detect NVIDIA devices and could not load kernel module nvidia in the VM

### ISSUE THREAD

**Issue by soulseen** [NVIDIA/libnvidia-container#170]
I followed this [doc](https://github.com/zvonkok/kata-containers/blob/nvidia/docs/use-cases/NVIDIA-GPU-passthrough-and-Kata.md#install-nvidia-driver--toolkit-in-kata-containers-guest-os) try to use Nvidia driver in kata-container.
the container was created in VM, and the Nvidia driver module works well in VM. but can not load Nvidia kernel module to the container by executing command `nvidia-container-cli` as OCI prestart hook.
I run `nvidia-container-cli` in the VM directly, it loads Nvidia kernel module success

here is the prestart hook command 
```
/usr/bin/nvidia-container-cli --load-kmods --debug=/tmp/nvidia-container-toolkit.log configure --device=all --utility --compute --pid=111 /run/kata-containers/fae4bba34fa4fd9bdbe9cba15bf7bac213db699d6219a267920afbbdd43a3e89/rootfs
``` 
 and the log is as follows:
```
-- WARNING, the following logs are for debugging purposes only --

I0506 06:40:20.504472 119 nvc.c:376] initializing library context (version=1.9.0, build=5e135c17d6dbae861ec343e9a8d3a0d2af758a4f)
I0506 06:40:20.504520 119 nvc.c:350] using root /
I0506 06:40:20.504523 119 nvc.c:351] using ldcache /etc/ld.so.cache
I0506 06:40:20.504526 119 nvc.c:352] using unprivileged user 65534:65534
I0506 06:40:20.504537 119 nvc.c:393] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I0506 06:40:20.504587 119 nvc.c:395] dxcore initialization failed, continuing assuming a non-WSL environment
W0506 06:40:20.505563 119 nvc.c:258] failed to detect NVIDIA devices
I0506 06:40:20.505715 123 nvc.c:278] loading kernel module nvidia
E0506 06:40:20.506795 123 nvc.c:280] could not load kernel module nvidia
I0506 06:40:20.506799 123 nvc.c:296] loading kernel module nvidia_uvm
E0506 06:40:20.507786 123 nvc.c:298] could not load kernel module nvidia_uvm
I0506 06:40:20.507790 123 nvc.c:305] loading kernel module nvidia_modeset
E0506 06:40:20.508728 123 nvc.c:307] could not load kernel module nvidia_modeset
I0506 06:40:20.508904 124 rpc.c:71] starting driver rpc service
I0506 06:40:20.518913 119 rpc.c:135] driver rpc service terminated with signal 15
I0506 06:40:20.518945 119 nvc.c:430] shutting down library context
```

run `nvidia-smi -L` in the VM:
```
root@kata-79cf45d755-s82p4:/# nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-fe3f1b7b-9e32-6afc-ba34-bc1213b1d642)
```

**Comment by soulseen** [comment]
@zvonkok hi, If you have also encountered this problem, could you please provide some help? thanks very much.

**Comment by zvonkok** [comment]
@soulseen I do not think this is a libnvidia-container issue, please reopen on kata-containers github page. When the modules cannot be even loaded this looks like there is not even a GPU device in your VM. 
```
W0506 06:40:20.505563 119 nvc.c:258] failed to detect NVIDIA devices
```
@elezar @klueska closing this not a toolkit issue.

**Comment by soulseen** [comment]
@zvonkok But the GPU device is actually already in the VM because I ran `nvidia-smi -L` in VM and get the output:
```
GPU 0: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-fe3f1b7b-9e32-6afc-ba34-bc1213b1d642)
```

**Comment by zvonkok** [comment]
@soulseen Since you're running kata, please first check if your kata setup is correct (e.g. are you using the guest_oci_hook setting etc) and then we can deep dive to see why the hook is not working. Did you check if you can run `nvidia-smi` in the container before digging into the VM? Create an issue on the kata-containers github and I can follow up from there.
