### ISSUE TITLE
installation instructions seem to be broken

### ISSUE THREAD

**Issue by stevvooe** [NVIDIA/libnvidia-container#18]
I followed the ubuntu instructions at https://nvidia.github.io/libnvidia-container/ and it resulted in a 404 and an apt broken because it was filled with html from the 404.

I had to manually find https://github.com/NVIDIA/libnvidia-container/blob/gh-pages/ubuntu16.04/libnvidia-container.list and add the file manually.

**Comment by 3XX0** [comment]
Right, we made it architecture agnostic and moved the `.list` one level above.
Thanks for the report, I will fix the documentation.

**Comment by stevvooe** [comment]
@3XX0 Also, when I finally did that, the packages were not found. I had to build the packages myself and installed them, but the tool had an error.

**Comment by 3XX0** [comment]
Do you still have the output of what went wrong? Aside from the `.list` the repository should just work

**Comment by 3XX0** [comment]
I updated the [instructions](https://nvidia.github.io/libnvidia-container/), feel free to reopen if you're still facing issues
