### ISSUE TITLE
Nvidia conatiner : cuda:11.0-base nvidia-smi unable to locate image locally.

### ISSUE THREAD

**Issue by sandipware** [NVIDIA/libnvidia-container#181]
Enviorment  as below :  
OS : Ubuntu  : Ubuntu 18.04.6 LTS (bionic)
CUDA : V10.1.105
Docker version : 20.10.17
Steps I followed for installation:
    [https://francismaria.medium.com/install-carla-simulator-in-ubuntu-18-04-ada78159bc4f](https://francismaria.medium.com/install-carla-simulator-in-ubuntu-18-04-ada78159bc4f)
    

After executing below steps I got the below error :
`sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
`
Error Description : 
**Unable to find image 'nvidia/cuda:11.0-base' locally
docker: Error response from daemon: manifest for nvidia/cuda:11.0-base not found: manifest unknown: manifest unknown.**

Any suggestion is appreciated.

**Comment by klueska** [comment]
I believe they end-of-lifed this image and you would need to use `nvidia/cuda:11.0.3-base` if you need an `11.0` image.

**Comment by sandipware** [comment]
Thanks loa for your help. 
Here is final command for other to refer :
  `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base nvidia-smi`
