### ISSUE TITLE
git file is too lagrge, can reduce some space.

### ISSUE THREAD

**Issue by zhaoxuat** [NVIDIA/libnvidia-container#185]
I download it very slow when i git clone. can we delete some git object, reduce some space.
![image](https://user-images.githubusercontent.com/27858842/190616324-979d8375-2686-483b-9654-c137fbe65ccc.png)

**Comment by elezar** [comment]
@zhaoxuat this repository also contains all our packages for the NVIDIA Container Toolkit in the `gh-pages` branch. You could consider performing a shallow clone, or fetching only the `main` branch while ignoring the `gh-pages` branch.

**Comment by zhaoxuat** [comment]
thanks.
