### ISSUE TITLE
status code 404 for developer.download.nvidia.com

### ISSUE THREAD

**Issue by doc-jay** [NVIDIA/libnvidia-container#189]
trying to install 'nvidia-docker2' on RHEL8.6.   running 'dnf install -y nvidia-docker2' and it returns:

```
Errors during downloading metadata for repository 'developer.download.nvidia.com_':
  - Status code: 404 for https://developer.download.nvidia.com/repodata/repomd.xml (IP: 152.195.19.142)
Error: Failed to download metadata for repo 'developer.download.nvidia.com_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by elezar** [comment]
The repo you mentioned is not associated with the components of the NVIDIA Container Toolkit and should not contain any dependencies for `nvidia-docker2`. Could you confirm whether this is a persistent error?

**Comment by doc-jay** [comment]
It was a bad repo after all.  Apologies
