### ISSUE TITLE
Linux Mint is missing from supported distributions

### ISSUE THREAD

**Issue by PlayerValley** [NVIDIA/libnvidia-container#195]
Linux Mint is based on Ubuntu, so it should work, but it doesn't.

i.e. Linux Mint is not listed on https://nvidia.github.io/libnvidia-container/

**Comment by elezar** [comment]
What do you mean it doesn't work. When following the instructions in the [documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit) please explicitly set the distrubution to `ubuntu18.04`:

```
 distribution=ubuntu18.04 \
      && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/experimental/$distribution/libnvidia-container.list | \
         sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
         sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
```

(or similar for the "experimental" repositories)

This should allow compatible packages to be installable for Linux Mint.
