### ISSUE TITLE
Pop!_OS 22.04 is not supported

### ISSUE THREAD

**Issue by mephist-helu** [NVIDIA/libnvidia-container#198]
When I test 
`distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list`,
__(knowing_ that $distribution is here **pop22.04**)_

It return always
\# Unsupported distribution!
\# Check https://nvidia.github.io/libnvidia-container.

So I have to manually specify this variable distribution to **ubuntu22.04** for it to work

**Comment by elezar** [comment]
Yes, `pop22.04` is not an officially supported distribution in that we don't qualify it as part of our release process. With that said, the `ubuntu18.04` packages are generally forward-compatible on all newer ubuntu-based distributions. Here the key is that the the glibc version available on the platform should be *at least* that used to build the `libnvidia-container*` packages for the system.
