### ISSUE TITLE
can't find libnvidia-container.so.1 

### ISSUE THREAD

**Issue by GodloveD** [NVIDIA/libnvidia-container#2]
I'm *finally* getting around to looking at this.  (Things have been quite busy.)  I can't see to get it to run. 

I'm running on a GCP GPU instance with Ubuntu Sever 16.04.  Here are the command I used to build, install, and run.
```
git clone https://github.com/NVIDIA/libnvidia-container.git
cd libnvidia-container/
sudo apt-get install bmake libcap-dev libseccomp-dev
make
sudo make install
nvidia-container-cli --help
```
It seems to build and install, but the last command yields:
```
nvidia-container-cli: error while loading shared libraries: libnvidia-container.so.1: cannot open shared object file: No such file or directory
```

**Comment by flx42** [comment]
You need to do:
```
sudo ldconfig
```
Otherwise the newly installed library isn't in `/etc/ld.so.cache`.

**Comment by GodloveD** [comment]
Ah.  Very helpful.  Thank you @flx42.
