### ISSUE TITLE
should the apt source list show 18.04?

### ISSUE THREAD

**Issue by georgettica** [NVIDIA/libnvidia-container#200]
using https://nvidia.github.io/libnvidia-container/ I found that using on an 22.04 machine returns a 18.04 sources list file.

this might work but making sure this is not an issue on your end

**Comment by elezar** [comment]
This is the expected behaviour and is called out in the [documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#linux-distributions). Please let us know if this could be clarified further.

I am closing this issue in the mean time.
