### ISSUE TITLE
make install provides a bmake no system rules error

### ISSUE THREAD

**Issue by ryandanehy** [NVIDIA/libnvidia-container#201]
Trying to install libnvidia-container, but when I run make install I get a bmake no system rules error. I am not familiar with bmake whatsoever so any ideas would be appreciated. 

`bmake[2]: no system rules (sys.mk).'

I don't seem to have usr/share/mk directory (not sure if that is important).

**Comment by elezar** [comment]
If possible, I would recommend using the containerized builds for the distribution closest to your target configurations. For example, for `ubuntu18.04-amd64` you would run:
```
make -f mk/docker.mk ubuntu18.04-amd64
```

This will generate the packages for the distributions / architecture combination in the `dist` folder.

**Comment by ryandanehy** [comment]
Thanks for the help, and it was totally on my end.
