### ISSUE TITLE
RHEL9 Repos Broken

### ISSUE THREAD

**Issue by Sc0th** [NVIDIA/libnvidia-container#203]
Possibly linked to #202 

libnvidia-container                                                                                                                                                       1.6 kB/s |  81  B     00:00
Errors during downloading metadata for repository 'libnvidia-container':
  - Status code: 404 for https://nvidia.github.io/libnvidia-container/stable/rhel9.0/x86_64/repodata/repomd.xml (IP: 185.199.109.153)
Error: Failed to download metadata for repo 'libnvidia-container': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by elezar** [comment]
Hi @Sc0th. Could you provide information as to how your `.repo` files were generated?

**Comment by Sc0th** [comment]
Hi,

Honestly & unhelpfully I cannot remember, they have been in play for around three months , stopped working on Saturday 6th.

**Comment by Sc0th** [comment]
Can ignore this, my apologies, found a typo.
