### ISSUE TITLE
Alpine Linux resp. non-glibc dependend compilation

### ISSUE THREAD

**Issue by mash-graz** [NVIDIA/libnvidia-container#21]
i know, that you usually refuse to support non-glibc based distributions in prrinciple, but it would be really useful, if we could utilize nvidia-docker also on [LinuxKit](https://github.com/linuxkit/linuxkit) as base for our diskless CUDA computing clusters. The core parts of LinuxKit are all build around Alpine Linux, because of it's extraordinary small size. there are various good reasons, why one may like this choice or wholeheartedly hate it, but we simply have to live with it.

porting the nvidia kernel drivers to Alpine linux resp. LinuxKit, was a trivial job, but i failed miserably, when i had to fight the RPC dependencies of libnvidia-container. :(

i already prepared a Dockerfile.alpine an the most obvious necessary makefile changes here:

 https://gitlab.com/mash-graz/libnvidia-container

but till now, i wasn't able to solve all the RPC related troubles during the compilation. :(
it looks like libnvidia-container should be able to utilize tirpc, which is already available as apk packge in alpine, but i couldn't figure out, if it could really work as a substitute?

would it be possible for you, to take a look on this particular issue?

i think, i could handle the rest myself.
and it's indeed an improvement, which could be of significant benefit to others as well. 

see:
https://github.com/linuxkit/linuxkit/issues/613
https://github.com/linuxkit/linuxkit/issues/2944
https://github.com/moby/moby/issues/23917

thanks!

**Comment by 3XX0** [comment]
Unfortunately we can't support any non-glibc platform.
libnvidia-container depends on driver libraries and the userspace driver is glibc only.
If you insist on trying to make it work, you can try to compile it on another system and see if musl handles it at runtime.

Something like `make dist WITH_TIRPC=yes WITH_LIBELF=yes`

**Comment by mash-graz** [comment]
thanks for this competent answer!

yes -- utilizing one of the available alpine-glibc-compatibility solutions (e.g.  https://github.com/sgerrand/alpine-pkg-glibc) was one of the possible workarounds, i was already thinking about...
it doesn't look like an optimal solution, because it makes pure nonsense of all this surrounding Alpine/musl asceticism, but you're right, this approach could [probably] work.

thanks!

**Comment by 3XX0** [comment]
I didn't mean to use alpine+glibc, although this would definitely fix the issue.
What I meant is that compiling on alpine is not strictly required. You can compile on another system with tirpc and libelf support and simply copy the tarball to your alpine system. Hopefully, musl won't choke on any symbols.
