### ISSUE TITLE
Debian 12 works totally fine with Debian 11 packages (which are Debian 10 packages)

### ISSUE THREAD

**Issue by labrat97** [NVIDIA/libnvidia-container#211]
Following the installation guide posted [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit), and testing with Debian 12, it appears that the old packages still work fine. I would recommend either sym-linking  Debian 12 _also_ to Debian 10's packages, or add a note in the documentation to set the `distribution` environment variable to `distribution=Debian11` for Debian 12.

**Comment by stefan-lange** [comment]
If it works, a symlink would be nice. I am still on 11.

Example of `/etc/apt/sources.list.d/nvidia-container-toolkit.list` for debian12
`deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/debian12/$(ARCH) /
#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/experimental/debian12/$(ARCH) /`

**Comment by elezar** [comment]
Please see our updated installation instructions. We now have generic deb packages and do not depend on specific distributions:

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

Closing this issue. Please reopen if there are still problems.
