### ISSUE TITLE
CAP_SYS_MODULE required even if not loading module

### ISSUE THREAD

**Issue by kpjensen** [NVIDIA/libnvidia-container#23]
Ran into this using `nvidia-docker` inside unprivileged LXC. I have dropped `CAP_SYS_MODULE` as the kernel module is already loaded on the host.

Any `nvidia-container-cli` command fails due to attempt to set CAP_SYS_MODULE
```
root@lxc:/# nvidia-container-cli list
nvidia-container-cli: permission error: capability change failed: operation not permitted
```
To test I removed CAP_SYS_MODULE here https://github.com/NVIDIA/libnvidia-container/blob/8245f6cd1facb480dbf17239e27a1a3584137e23/src/nvc_internal.h#L95 and then it works fine.

**Comment by 3XX0** [comment]
Will be fixed in the next release.
I'm curious though, how did you hit the issue? Did you explicitly drop `CAP_SYS_MODULE` in your config?

**Comment by kpjensen** [comment]
I explicitly drop `CAP_SYS_MODULE ` in my LXC config.

**Comment by 3XX0** [comment]
This should now be fixed in RC 2.
