### ISSUE TITLE
Warning of Key is stored in legacy trusted.gpg keyring 

### ISSUE THREAD

**Issue by DemonRx** [NVIDIA/libnvidia-container#232]
When running `sudo apt update`, the following warning appears:

```bash
W: https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

**Comment by elezar** [comment]
I would assume that your repo was updated using older instructions that still used `apt-key`. My recommendation is to remove any references to `nvida.github.io` in `/etc/apt/sources.list.d` and then follow our latest instructions https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt to reconfigure the repositories for the NVIDIA Container Toolkit.

**Comment by DemonRx** [comment]
@elezar updated  the script to point to the correct repo, and all is working as expected. 

Thank you :100:
