### ISSUE TITLE
Broken link on Unsupported Distribution github page

### ISSUE THREAD

**Issue by fritz-fritz** [NVIDIA/libnvidia-container#277]
Typically when adding a repo I tend to navigate directly to it in the browser to verify the contents won't conflict unexpectedly with other sources before I add it. For this project I don't get served a directory listing as I typically would (I suppose as it is Github Pages). Instead I get a (very pretty) error page.

I would suggest adding a link to the assets [https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/](https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/) if possible as I found via another issue here.

But regarding the reason for this issue, the link for "unsupported distribution" points to for example `https://nvidia.github.io/libnvidia-container/stable/deb/amd64/%22https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#linux-distributions%22` when browsing to `https://nvidia.github.io/libnvidia-container/stable/deb/amd64/`

**Comment by elezar** [comment]
Thanks @fritz-fritz.

I have updated the 404 page, fixing the link and adding some additional content regarding the GitHub pages repo.

If there is additional information that you would like to see feel free to create a PR to the `gh-pages` branch to update the documentation [here](https://github.com/NVIDIA/libnvidia-container/blob/gh-pages/404.md).

**Comment by fritz-fritz** [comment]
Looks good!
