### ISSUE TITLE
Document your build requirements

### ISSUE THREAD

**Issue by stevvooe** [NVIDIA/libnvidia-container#28]
This thing is impossible to build and you have to scour the internet to track down the necessary packages. Please document which packages are required and where to get them.

**Comment by flx42** [comment]
May I know why you aren't using the prebuilt packages or building inside a docker container?

The Dockerfile is probably the best reference:
https://github.com/NVIDIA/libnvidia-container/blob/master/mk/Dockerfile.ubuntu

Or similarly, the travis file:
https://github.com/NVIDIA/libnvidia-container/blob/master/.travis.yml

**Comment by stevvooe** [comment]
@flx42 Mostly because nothing works. ;)

I am trying to understand the build requirements and can't necessarily use a container for the build.

I can use those files, for now.

**Comment by flx42** [comment]
By the way, we will check-in `nvml.h` and `cuda.h` in the git repository directly, this way you will be able to build the library without any unofficial deb repository.
