### ISSUE TITLE
does nvidia-container support gpu virtualization?

### ISSUE THREAD

**Issue by tobyfan1980** [NVIDIA/libnvidia-container#29]
According to the document, we can specify which GPUs to be used on each container. My question is can different containers share the same set GPUs?

**Comment by flx42** [comment]
Yes, two containers can share the same GPU if you run them this way.

But it's not "GPU virtualization", containers are not VMs even if they are often compared to VMs.

**Comment by tobyfan1980** [comment]
Thanks for your answer. That helps.
