### ISSUE TITLE
Is it necessary for cuda to be on the host?

### ISSUE THREAD

**Issue by GodloveD** [NVIDIA/libnvidia-container#3]
```
$ nvidia-container-cli list
nvidia-container-cli: initialization error: cuda error: unknown error
```
I don't have cuda installed on this host.  But the expectation is that cuda will be installed in the container right?  Is it necessary for cuda to exist on the host for this to work?

**Comment by flx42** [comment]
The CUDA toolkit is not needed, but the driver obviously is.

Please run the following:
```
nvidia-container-cli --debug=/tmp/libnvidia-container.txt list --compute
```
And share the content of the log file. 

Also, does `nvidia-smi` work fine on the host?

Thanks for testing our library! :)

**Comment by GodloveD** [comment]
OK.  Bear with me here.  I'm sure I'm doing something stupid.  

First, you caught me.  I installed the NVIDIA driver on my GCP instance some days ago.  But when I stopped it and brought it back up the kernel modules were not loaded.  So I reinstalled the driver, but I still got the same error.  

Then I thought that maybe the driver has to be installed and functional when libnvidia-container is installed so I brought up a new vm with a K80, installed driver v384.66 and tried again.  But now I'm running into this error when I try to `make`.
```
/home/david/libnvidia-container/src/driver.c:20:18: fatal error: cuda.h: No such file or directory
```
`nvidia-smi` functions as expected.  When I search for `cuda.h` it I get this:
```
$ sudo find / -name cuda.h
/usr/src/linux-headers-4.10.0-32/include/uapi/linux/cuda.h
/usr/src/linux-headers-4.10.0-32/include/linux/cuda.h
/usr/include/linux/cuda.h
```
What gives?

**Comment by flx42** [comment]
You need the CUDA toolkit when **building** the library once, not when deploying it on other machines. We will soon provide deb/rpm packages so you won't have to build it yourself.

Those `cuda.h` headers you have are totally unrelated to NVIDIA CUDA :)
To get our CUDA toolkit, you can take a look at our `.travis.yml` file:
https://github.com/NVIDIA/libnvidia-container/blob/master/.travis.yml#L32-L42

**Comment by GodloveD** [comment]
Clear and helpful as always.  Thanks @flx42.  I guess I actually did have cuda installed on my previous vm.  Spun it up a few days ago for a totally different purpose and forgot what all I installed on it.  Great way to do reproducible debugging.  😜

**Comment by GodloveD** [comment]
Whoops.  Closed too soon.  Still getting the same error.  
```
$ nvidia-container-cli list
nvidia-container-cli: initialization error: cuda error: unknown error
```
Driver seems to be working just fine:
```
$ nvidia-smi
Thu Aug 17 19:20:43 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0    71W / 149W |      0MiB / 11439MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by flx42** [comment]
Please share the log then, as explained in https://github.com/NVIDIA/libnvidia-container/issues/3#issuecomment-323125731

**Comment by GodloveD** [comment]
Of course.
```

-- WARNING, the following logs are for debugging purposes only --

I0817 19:32:04.929374 17191 nvc.c:250] initializing library context (version=1.0.0, build=b48951f2727f15ada9a42498e9d5dd1aec73c013)
I0817 19:32:04.929410 17191 nvc.c:225] using ldcache /etc/ld.so.cache
I0817 19:32:04.929414 17191 nvc.c:226] using unprivileged user 1001:1002
I0817 19:32:04.930538 17192 driver.c:127] starting driver service
I0817 19:32:04.933269 17191 driver.c:201] driver service terminated with signal 15
```

**Comment by flx42** [comment]
Interesting, what's your distro?

**Comment by GodloveD** [comment]
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

$ uname -a
Linux gpu-2 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by 3XX0** [comment]
@GodloveD our latest drivers require UVM, can you make sure that the driver is fully loaded.

This  should do it:
`sudo nvidia-container-cli -k -d /dev/tty list -cuv`

**Comment by GodloveD** [comment]
OK.  That got it working.  Thanks @3XX0.

**Comment by pcolton** [comment]
I'm getting same error, can't seem to resolve it:

> ubuntu@GPU-Test-1:~$ sudo nvidia-container-cli -k -d /dev/tty list
> 
> -- WARNING, the following logs are for debugging purposes only --
> 
> I0214 23:59:15.021630 3558 nvc.c:250] initializing library context (version=1.0.0, build=4a618459e8ba522d834bb2b4c665847fae8ce0ad)
> I0214 23:59:15.055619 3558 nvc.c:170] loading kernel module nvidia
> I0214 23:59:15.055857 3558 nvc.c:182] loading kernel module nvidia_uvm
> I0214 23:59:15.055959 3558 nvc.c:190] loading kernel module nvidia_modeset
> I0214 23:59:15.056056 3558 nvc.c:225] using ldcache /etc/ld.so.cache
> I0214 23:59:15.056081 3558 nvc.c:226] using unprivileged user 65534:65534
> I0214 23:59:15.057475 3559 driver.c:134] starting driver service
> I0214 23:59:15.058672 3558 driver.c:208] driver service terminated with signal 15
> nvidia-container-cli: initialization error: cuda error: unknown error

**Comment by 3XX0** [comment]
@pcolton most likely a driver issue, which driver version are you running? Does CUDA work on your host? Anything suspicious in `dmesg`?

**Comment by mcheshkov** [comment]
@pcolton I had similar symptoms, after rebooting everything works well

**Comment by maingoh** [comment]
I sometimes get the same issues (works after rebooting). Same logs than @pcolton using `nvidia-container-cli -k -d /dev/tty list`.

In `dmesg` the only suspicious thing that I find is: 
```
[Mon Mar 19 08:00:19 2018] nvidia 0000:23:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000e address=0x0000000000000000 flags=0x0000]
```

OS: ubuntu 17.10 (using nvidia-docker2 packages for ubuntu 16.04)
Nvidia driver: 384.111
Docker version 17.12.1-ce, build 7390fc6
Nvidia docker version: 2.0.3+docker17.12.1-1

`nvidia-smi` works fine on the host.

**Comment by sheinbergon** [comment]
This still happens with: 
* Ubuntu 18.04
* Nvidia Docker 2.0.3,
* Nvidia Driver 390.48
* libnvidia-container1 1.0.0 rc.2-1
* nvidia-container-runtime 2.0.0 
* docker 18.06

Secure boot is off, nvidia_uvm kernel module is loaded.

Any suggestions are welcome

**Comment by vochicong** [comment]
The same error happens here for nvidia-driver-410, Ubuntu 18.04 LTS.
I'm going to try nvidia-driver-415.

**Comment by zym1010** [comment]
> The same error happens here for nvidia-driver-410, Ubuntu 18.04 LTS.
> I'm going to try nvidia-driver-415.

415 failed as well (on Ubuntu 14.04 and CentOS 7)

**Comment by RenaudWasTaken** [comment]
Hello!

Try running `sudo nvidia-container-cli -k -d /dev/tty list`

**Comment by zym1010** [comment]
> Hello!
> 
> Try running `sudo nvidia-container-cli -k -d /dev/tty list`

yes this is a workaround. hopefully this can get solved fully in the future.

**Comment by RenaudWasTaken** [comment]
Actually, I'm guessing the permissions were wrong on some files, this should have fixed some of the permissions and you shouldn't need sudo anymore

**Comment by zym1010** [comment]
> Actually, I'm guessing the permissions were wrong on some files, this should have fixed some of the permissions and you shouldn't need sudo anymore

I think sudo or not is not that relevant for me; it would be perfect if `nvidia-container-cli -k` is totally not needed.

**Comment by vochicong** [comment]
415 also failed.

I find that the error will always happen if I run a Cuda container overnight,
e.g. https://github.com/vochicong/lc0-nvidia-docker

**Comment by vochicong** [comment]
I was able to solve the problem by removing all nvidia and cuda packages then reinstall them.

```
 sudo apt-get purge nvidia-docker2 nvidia-container-runtime cuda
 sudo apt-get autoremove
 sudo apt-get autoclean

 sudo apt-get update
 sudo apt-get install -y nvidia-docker2 cuda
 sudo pkill -SIGHUP dockerd
 
 cat /proc/driver/nvidia/version
 nvidia-smi 
 docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi

```

**Comment by RenaudWasTaken** [comment]
> [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real 
--device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,
driver<385 --pid=22284 /var/lib/docker/overlay2/af1f3a75474eed5f9f3dc57945b250373997bfdf921dc8da9d9716a822777969/merged]
\\\\nnvidia-container-cli: initialization error: cuda error: forward compatibility was attempted on non supported hw\\\\n\\\"\"": unknown.

As indicated in the error you tried to run a cuda container that has forward compat (CUDA 10.0) with a configuration not supported.
Upgrading your driver should have fixed the issue :)

**Comment by vochicong** [comment]
> Upgrading your driver should have fixed the issue :)

The error happens again, now I'll try `NVIDIA-Linux-x86_64-410.93.run`
for my GEFORCE RTX 2080 Ti

**Comment by vochicong** [comment]
Things work again after re-installing the latest NVIDIA driver above.
https://gist.github.com/vochicong/6f1b5f1e5210dcd2a4a550cd2b55ab3d

**Comment by wanglinteng** [comment]
> Hello!
> 
> Try running `sudo nvidia-container-cli -k -d /dev/tty list`

thanks！
