### ISSUE TITLE
Honor DOCKER_RAMDISK environment variable

### ISSUE THREAD

**Issue by Ricordel** [NVIDIA/libnvidia-container#31]
Docker supports an environment variable called `DOCKER_RAMDISK` that, if set, will tell `runc` not to use `pivot_root` but an alternative way of chrooting. This is needed to run Docker from a ramfs, which is exactly my use case.

The toplevel use of that variable can be seen here: https://github.com/moby/moby/blob/c3a02077149ea8ee1d53b2b60a3d36c29d1505f8/libcontainerd/client_daemon.go#L305
and the `NoPivotRoot` option is then propagated through `dockerd` and `containerd` down to `runc`, that selects a way of changing the rootfs according to it (and other params, see https://github.com/opencontainers/runc/blob/63e6708c74c1cc46091ec92ea9df5aca4d82e803/libcontainer/rootfs_linux.go#L102)

Unfortunately, `libnvidia-container` does not honor this parameter and uses `SYS_pivot_root` unconditionally to change the rootfs (https://github.com/NVIDIA/libnvidia-container/blob/master/src/nvc_ldcache.c#L117). As a result, it's impossible to use `nvidia-docker` from an initramfs, typically on a diskless machine.

Is it possible to do something equivalent to what `runc` does? I will give it a try myself, but all this is quite an unknown territory for me, so any help is appreciated, either to do it for me (that would be lovely :-) ), explain me how to do it, or tell me that it's not possible.

**Comment by flx42** [comment]
This seems like a reasonable ask, @3XX0  what do you think? (he's out this week though)
Not sure if we should add a CLI flag like `runc`, or if we should try to detect this situation like LXC.

**Comment by Ricordel** [comment]
As far as it goes, I have something working based on checking for the environment variable, I don't know if that's a satisfying implementation (one again, I'm quite new to this).
Pull request coming tomorrow morning (UTC+1) so you can see what you think about it.

**Comment by flx42** [comment]
We definitely don't want to rely on this environment variable :), libnvidia-container works outside of docker.
Again, we could either do like LXC:
https://github.com/lxc/lxc/blob/b988d228d1868e9bee6e7e4ded1eee859c4716fe/src/lxc/conf.c#L1580-L1591
https://github.com/lxc/lxc/blob/b988d228d1868e9bee6e7e4ded1eee859c4716fe/src/lxc/utils.c#L1297-L1342

Or like runc with `runc run --no-pivot`.

I would defer to @3XX0 for the decision.

**Comment by Ricordel** [comment]
Oh yes that's something I should have thought about.
Well I'll send my PR with the `if (use_pivot_root())`

**Comment by Ricordel** [comment]
Oh yes that's something I should have thought about.

I'll send my PR with an `if (no_pivot_root())` clearly separated from the rest so that you can plug in what you feel is right (or just do it from scratch if my code is broken).

**Comment by RenaudWasTaken** [comment]
Closing as there doesn't seem to be anything to do.

**Comment by Ricordel** [comment]
Sorry but why is there nothing to do? The code still calls `SYS_pivot_root` unconditionally, which will still fail with an initramfs.

**Comment by RenaudWasTaken** [comment]
Reasonable enough, I don't think I read this issue properly before closing it, sorry.
We will look into this, though this isn't a very high priority

**Comment by Ricordel** [comment]
I understand perfectly that this is a corner case. If you give me a hint on which strategy you'd like (

**Comment by klueska** [comment]
Can this ticket now be closed with the introduction of the `--no-pivot-root` flag in the `1.1.0` release?

**Comment by elezar** [comment]
Since there has been no response, I am closing this issue.

@Ricordel please reopen / create a new issue if the `--no-pivot-root` option does not address the issue.

**Comment by Ricordel** [comment]
Sorry for the **HUGE** delay responding, this subject got out of my radar during a long time.

After finally coming back to it, I tested with `1.4.0` and the `--no-pivot-root` flag works just fine, thank you for including it.

**Comment by elezar** [comment]
Just a note. A fix was merged in https://gitlab.com/nvidia/container-toolkit/libnvidia-container/-/merge_requests/175 that ensures that the LDCache is updated when the `--no-pivot-root` option is specified.
