### ISSUE TITLE
Unable to sync packages to foreman

### ISSUE THREAD

**Issue by gnekic** [NVIDIA/libnvidia-container#33]
I'm trying to sync the RHEL based distro to foreman, and it fails. Foreman does not support a sha512 checksum type. 

Here is the error that I'm getting 
"PLP1005: The checksum type 'sha512' is unknown."

Can you create a repo with a sha256 checksum? It will allow my team to use these packages as part of our automation.

**Comment by klueska** [comment]
Is this still an issue you are having or is it OK to close this issue now?

**Comment by elezar** [comment]
@gnekic since there has been no response to our last comment, I'm going to go ahead and close this issue. Please reopen if it is still relevant.
