### ISSUE TITLE
CUDA Error encountered during standard ongoing operation

### ISSUE THREAD

**Issue by sheinbergon** [NVIDIA/libnvidia-container#34]
Installed Host os software versions:

* Ubuntu 18.04.1
* Nvidia Docker 2.0.3
* Nvidia Driver 390.48
* libnvidia-container1 1.0.0 rc.2-1
* nvidia-container-runtime 2.0.0
* Docker CE 18.06
* Secure boot is off, nvidia_uvm kernel module is loaded upon boot, of course.

We are running FFmpeg compiled with nvenc inside a container deriving from cuda:16.04-cuda-9.1 image for prolonged duration, and sometimes the FFmpeg command just starts hangs. Trying to run any CUDA related container or container operation beyond that point, such as:

`docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi`

or

`nvidia-container-cli -k -d /dev/tty list.`

results in the following error:

`nvidia-container-cli: initialization error: cuda error: unknown error`

nvidia-smi works on the host os without an issue.

Rebooting the machine resolves the issue, **but that's less than desirable**, and yes - we know this has already been discussed in #3 a year ago.

@flx42 @3XX0  any advice or help is welcomed

**Comment by 3XX0** [comment]
Are you launching multiple containers or just one which ends up hanging?
Do you have `nvidia-persistenced` running on the host?

This is most likely a driver issue. Anything interesting in the logs produced by `nvidia-container-cli -k -d /dev/tty list` or `dmesg`?

**Comment by sheinbergon** [comment]
@3XX0  we are launching a single container that uses the `nvidia `runtime , and it's only one becoming faulty. We are using the standard `runc` for the other container, which are running just fine.

Yes, the `nvidia-persiatenced` systemd service is available and alive.

 I ran the above `nvidia-container-cli` command and got the same cuda error as described in the issue itself.
@asaf-halili  if this issue reoccurrs, could you run the above command and paste the output in here?
Also, I checked the `dmesg` or `/var/log/kern.log` and didn't see a single error message. Better search the last one again for any specific errors that happened on the 6/9

@3XX0 @flx42 would upgrading the driver to 396.xx help? Any further steps we may take to provide you with additional information?

**Comment by 3XX0** [comment]
Yes try upgrading to the latest LTS driver 396.XX see if it fixes the issue.

**Comment by asaf-halili** [comment]
Thanks @3XX0.

We upgraded the driver and we are checking if it fixed the issue.

**Comment by sheinbergon** [comment]
@3XX0 BTW, you asked for the output of `nvidia-container-cli` with 390 version on error scenario - here it is

```
-- WARNING, the following logs are for debugging purposes only --

I0915 11:25:32.640754 17665 nvc.c:281] initializing library context (version=1.0.0, build=e3a2035da5a44b8a83d9568b91a8a0b542ee15d5)
I0915 11:25:32.640786 17665 nvc.c:255] using root /
I0915 11:25:32.640789 17665 nvc.c:256] using ldcache /etc/ld.so.cache
I0915 11:25:32.640792 17665 nvc.c:257] using unprivileged user 65534:65534
I0915 11:25:32.643691 17667 nvc.c:191] loading kernel module nvidia
I0915 11:25:32.643931 17667 nvc.c:203] loading kernel module nvidia_uvm
I0915 11:25:32.644110 17667 nvc.c:211] loading kernel module nvidia_modeset
I0915 11:25:32.644611 17669 driver.c:136] starting driver service
I0915 11:25:32.647100 17665 driver.c:228] driver service terminated with signal 15
nvidia-container-cli: initialization error: cuda error: unknown error
```

**Comment by sheinbergon** [comment]
@3XX0 We can confirm upgrading to 396.x had resolved the issue.
