### ISSUE TITLE
Problems with "no cuda-capable device is detected" after Ubuntu upgrade

### ISSUE THREAD

**Issue by hmeine** [NVIDIA/libnvidia-container#37]
I have upgrade from Ubuntu 16.04 LTS to 18.04 LTS and cannot get nvidia-docker2 to work anymore.  I tried removing all nvidia packages and reinstalling from scratch.  The command I use for testing now is `docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi`, which gives:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=4489 /var/lib/docker/aufs/mnt/5094d003411b0b81bdd4d54af77ed4099e2c6a65ba91923b5821c75f6dbb9c87]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.
zsh: exit 125   docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi
```

`nvidia-container-cli info` gives me:
```
NVRM version:   390.87
CUDA version:   9.1

Device Index:   0
Device Minor:   0
Model:          GeForce GTX 1080 Ti
Brand:          GeForce
GPU UUID:       GPU-c585f5ec-e9bf-682d-7d19-12e0a2f0bba4
Bus Location:   00000000:01:00.0
Architecture:   6.1
```

`nvidia-smi` also works fine:
```
Tue Oct  9 16:55:20 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
| 23%   42C    P8    11W / 250W |     30MiB / 11176MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1518      G   /usr/lib/xorg/Xorg                            27MiB |
+-----------------------------------------------------------------------------+
```

Of course I tried searching for the error message, but could not find any relevant findings.  Do you have any suggestions what could go wrong here, or how to find out / get out of this situation?

**Comment by hmeine** [comment]
Some of the presumably irrelevant hits pointed to wrong device permissions, which I tried to rule out.
```
crw-rw---- 1 root vglusers 195,   0 Okt  9 16:27 /dev/nvidia0
crw-rw---- 1 root vglusers 195, 255 Okt  9 16:27 /dev/nvidiactl
crw-rw---- 1 root vglusers 195, 254 Okt  9 16:27 /dev/nvidia-modeset
crw-rw-rw- 1 root root     236,   0 Okt  9 16:27 /dev/nvidia-uvm
crw-rw-rw- 1 root root     236,   1 Okt  9 16:31 /dev/nvidia-uvm-tools
```
I am in the `vglusers` group, and I also temporarily changed them all to mode 0666.

**Comment by 3XX0** [comment]
So `nvidia-container-cli info` works but `docker run` doesn't?
Can you always reproduce it? That's weird, both of them should either work or fail.

**Comment by hmeine** [comment]
Yes, exactly. docker run with nvidia runtime always fails, but I find no other problem.

**Comment by 3XX0** [comment]
Can you try setting `user = "root:vglusers"` in `/etc/nvidia-container-runtime/config.toml`

**Comment by hmeine** [comment]
Jackpot! 👍 At last, I am able to run nvidia-docker again! :-)

I must admit that I am still very puzzled – after all, I even tried with rw permissions for "other". Furthermore, I know several people with Ubuntu 18.04 who did not seem to have to do this (but I will double-check again, now that I know more).

**Comment by hmeine** [comment]
Ok, just confirmed: on a machine with 18.04 installed from scratch and NVRM version 390.77, the config entry is missing (actually, default is a commented out `#user = "root:video"`), and dev permissions are:
```
crw-rw-rw- 1 root root 195,   0 Sep 24 13:59 /dev/nvidia0
crw-rw-rw- 1 root root 195,   1 Sep 24 13:59 /dev/nvidia1
crw-rw-rw- 1 root root 195,   2 Sep 24 13:59 /dev/nvidia2
crw-rw-rw- 1 root root 195,   3 Sep 24 13:59 /dev/nvidia3
crw-rw-rw- 1 root root 195, 255 Sep 24 13:59 /dev/nvidiactl
crw-rw-rw- 1 root root 195, 254 Sep 24 17:43 /dev/nvidia-modeset
crw-rw-rw- 1 root root 238,   0 Sep 24 13:59 /dev/nvidia-uvm
crw-rw-rw- 1 root root 238,   1 Sep 24 17:43 /dev/nvidia-uvm-tools
```

**Comment by 3XX0** [comment]
Yeah, permissions of the device files are dictated by the kernel module parameters and those can vary depending on how you install the driver. Hence the setting ;)

**Comment by hmeine** [comment]
Thanks again. For completeness, I asked another colleague who has the same upgrade history AND the same driver version, and STILL the permissions are different, and she does not need that setting.

**Comment by hmeine** [comment]
I found the culprit: At some point in the past, I had virtualgl installed. Uninstalling that left two configuration files, which I had to remove:

`/etc/udev/rules.d/99-virtualgl-dri.rules` contained

    KERNEL=="card[0-9]", MODE="0660", OWNER="root", GROUP="vglusers"

and `/etc/modprobe.d/virtualgl.conf` contained:

    options nvidia NVreg_DeviceFileUID=0 NVreg_DeviceFileGID=1005 NVreg_DeviceFileMode=0660

I removed both files, ran `update-initramfs -u` in order to let the changed options take effect, and did `delgroup vglusers` (which was 1005, of course), and now I could revert the definition of `user` in `/etc/nvidia-container-runtime/config.toml`.

**Comment by romangrothausmann** [comment]
Many thanks @3XX0 for the support, https://github.com/NVIDIA/libnvidia-container/issues/37#issuecomment-428368324 solved the problem for us. Is there anything else to consider if we want to use nvidia-docker and VirtualGL on the same machine?
