### ISSUE TITLE
gpu on windows container

### ISSUE THREAD

**Issue by kingofthebongo2008** [NVIDIA/libnvidia-container#38]
hi
since you do not have an implementation for windows.
where i can read or briefly what i need to do, to have nvidia gpu on a windows container. i want to make unit tests with directx 12 in a docker environment with hardware acceleration

**Comment by 3XX0** [comment]
Unfortunately, Windows is not supported and we have no plan to support it atm

**Comment by kingofthebongo2008** [comment]
hey, i understand this.
i am curious what needs to be done in general to support this.
this involves work from microsoft to expose gpu to windows containers or it an nvidia issue.
i have asked similar question to amd since they also have similar library
