### ISSUE TITLE
LXC hook failed to run out of the box

### ISSUE THREAD

**Issue by billyauhk** [NVIDIA/libnvidia-container#39]
**Background**: On a newly installed Ubuntu box, I am trying to start a container in LXC but it fails to start once I set nvidia.runtime="true". I frantically traced the error to the last line of the `/usr/share/lxc/hooks/nvidia` LXC hook, which is a line calling `nvidia-container-cli`. The exec call should be something like (extracted with a very long `strace` log):

`LXC_CONFIG_FILE=/var/log/lxd/abc/lxc.conf LXC_LOG_LEVEL=ERROR LXC_ROOTFS_MOUNT=/usr/lib/x86_64-linux-gnu/lxc LXC_NAME=abc http_proxy= NVIDIA_VISIBLE_DEVICES=none LD_LIBRARY_PATH=/usr/lib/lxd/ LXC_CONSOLE_LOGPATH=/var/log/lxd/abc/console.log LXC_ROOTFS_PATH=/var/lib/lxd/containers/abc/rootfs NVIDIA_DRIVER_CAPABILITIES=compute,utility PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/sbin:/usr/bin:/sbin:/bin LISTEN_FDNAMES=lxd.socket PWD=/ LANG=en_HK.UTF-8 LXC_HOOK_VERSION=0 SHLVL=0 LANGUAGE=en_HK:en LXC_CGNS_AWARE=1 LVM_SUPPRESS_FD_WARNINGS=1 nvidia-container-cli --user configure --no-cgroups --ldconfig=@/sbin/ldconfig.real --compute --utility /usr/lib/x86_64-linux-gnu/lxc`

**Problem**: Inside the above `nvidia-container-cli` execution something goes wrong (and thus my LXC hook failed and LXC complains it could not start the container). When running that on command line directly, I got message like:

`nvidia-container-cli: container error: stat failed: /usr/lib/x86_64-linux-gnu/lxc/proc/13970: no such file or directory` (of course the PID would change every time but I don't think it is relevant from the moment).

My current understanding of the situation is that `nvc_container_new()` somehow failed to continue since it failed to find the named folder with `stat()` syscall (might be `fstat()` as I used `strace` to make my guess), but I have no clue on the exact line of code which is searching for that particular folder.

Could anyone pls help resolving the problem as it is rather sad when things don't work even in a clean box. I am willing to dig deeper into the root cause but failed to get significant progress with `strace()` so would like some help from people who are more knowledge in how `nvc_container_new()` works.

----
**Software Versions** (I specifically re-installed the machine so that it is "clean" enough for easier reproduction of the issue):
OS: Ubuntu 16.04.5 (kernel: 4.4.0-131-generic)
Packages installed after a "apt-get update && apt-get upgrade" of a blank Ubuntu
CUDA: 10.0.130-1, Driver 410.72 installed via `developer.download.nvidia.com/compute/cuda/repos`
LXC: 3.0.2 from ppa:ubuntu-lxc/stable (lxc lxcfs)
LXD: 3.0.2 from xenial-backports (xenial-backports lxd lxd-client)
ZFS (apt-get zfsutils-linux)
nvidia-container-runtime installed via `https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/nvidia-container-runtime.list` (thus `libnvidia-container` installed as its dependency)

**Comment by klueska** [comment]
Is this still an issue you are having or is it OK to close this issue now?

**Comment by billyauhk** [comment]
@klueska I am not having the issue now -- the project got killed as we were not able to progress
