### ISSUE TITLE
Gentoo ebuild - help needed

### ISSUE THREAD

**Issue by archenroot** [NVIDIA/libnvidia-container#42]
I have created basic package for Gentoo (form of ebuild file). I got stuck on error:
```
 fatal error: rpc/rpc.h: No such file or directory
 #include <rpc/rpc.h>

```
I can find such file in multiple packages:
```
app-crypt/mit-krb5-1.16-r2 (/usr/include/gssrpc/rpc.h)
dev-libs/libevent-2.1.8 (/usr/include/event2/rpc.h)
net-libs/libtirpc-1.0.2-r1 (/usr/include/tirpc/rpc/rpc.h)
sys-kernel/gentoo-sources-4.14.65 (/usr/src/linux-4.14.65-gentoo/drivers/staging/lustre/lnet/selftest/rpc.h)
sys-kernel/gentoo-sources-4.14.78 (/usr/src/linux-4.14.78-gentoo/drivers/staging/lustre/lnet/selftest/rpc.h)
sys-libs/glibc-2.27-r6 (/usr/src/debug/sys-libs/glibc-2.27-r6/glibc-2.27/include/rpc/rpc.h)
sys-libs/glibc-2.27-r6 (/usr/src/debug/sys-libs/glibc-2.27-r6/glibc-2.27/sunrpc/rpc/rpc.h)

```
What is correct package to use from (I suspect its glibc). I will try to include in Makefile.

Thank you.

**Comment by archenroot** [comment]
Ok, thx to this:
[Gentoo archive](https://archives.gentoo.org/gentoo-user/message/e67468b9f7d04e3b4d347b2738c56b1e
)
I understand on Gentoo rpc.h lives under one more subdir:
```
venus /tmp/portage/dev-libs/nvidia-container-1.0.0/work/nvidia-container-1.0.0 # locate tirpc/rpc/rpc.h
/usr/include/tirpc/rpc/rpc.h
```

**Comment by archenroot** [comment]
I extended Makefile into following form (last line change):
```
CFLAGS   := -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden \
            -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull \
            -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow \
            -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion \
            -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression \
            -I/usr/include/tirpc -Wl,-ltirpc $(CFLAGS)
```
Now I can compile.

**Comment by archenroot** [comment]
Ok, I also failed because of default destination /usr/lib, which on gentoo AMD64 is lib64, all 3 small patches including Gentoo ebuild are available here:
https://github.com/archenroot/gentoo-overlay/tree/master/dev-libs/nvidia-container

But I have now question: **### What to do next to bring full runtime to gentoo?**

**Comment by archenroot** [comment]
From Strace I can see:
```
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(4)                                = 0
close(5)                                = -1 EBADF (Bad file descriptor)
close(3)                                = 0
write(2, "nvidia-container-cli: ", 22nvidia-container-cli: )  = 22
write(2, "initialization error: cuda error"..., 68initialization error: cuda error: no cuda-capable device is detected) = 68
write(2, "\n", 1

```
If I understand this correctly the error returned from CUDA API is error code 68 which points me to:
[](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038)

Error explanation is:
```
CudaErrorSyncDepthExceeded = 68
This error indicates that a call to cudaDeviceSynchronize made from the device runtime failed because the call was made at grid depth greater than than either the default (2 levels of grids) or user specified device limit cudaLimitDevRuntimeSyncDepth. To be able to synchronize on launched grids at a greater depth successfully, the maximum nested depth at which cudaDeviceSynchronize will be called must be specified with the cudaLimitDevRuntimeSyncDepth limit to the cudaDeviceSetLimit api before the host-side launch of a kernel using the device runtime. Keep in mind that additional levels of sync depth require the runtime to reserve large amounts of device memory that cannot be used for user allocations.
```

**Comment by RenaudWasTaken** [comment]
Hello !

Is the NVIDIA driver installed on the machine?

**Comment by archenroot** [comment]
@RenaudWasTaken - sure, I can run CUDA query device and run glxspehres64 which displays correct device....

**Comment by archenroot** [comment]
Let me check....

**Comment by archenroot** [comment]
In general I would like to have Gentoo host on multigpu node where I can run all AI layers all the time within its own docker image, so each can have specific env config.

**Comment by kinzess** [comment]
@archenroot env config? no, i think you should change user.

```
 ~/libnvidia-container # nvidia-container-cli info
nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected

~/libnvidia-container # nvidia-container-cli --user=0:33 info 
NVRM version:   390.25
CUDA version:   9.1

Device Index:   0
Device Minor:   0
Model:          GeForce GTX 960M
Brand:          GeForce
GPU UUID:       GPU-a7ba524a-ed1f-4402-1ac8-d562f3cc572f
Bus Location:   00000000:02:00.0
Architecture:   5.0
```

**Comment by archenroot** [comment]
@kinzess - I run under my standard user, but let thx for hints... will look soon into this.

**Comment by angryvincent** [comment]
a side note on a problem.
libnvidia-container building steps involves fetching its deps (elfutils, libtiirpc, etc) and build them internally and links against them. This is sort of a problem for the source based distribution. libelf, libtirpc, libseccom can be installed by package manager and it would be really nice to have build system aware of such case. It, perhaps, a separate issue for developers, but i interested in gentoo, personally, hence a comment here.

**Comment by RenaudWasTaken** [comment]
Sorry for the long delay in answering this.

Can you run `sudo nvidia-container-cli -k -d /dev/tty list` ?
If possible can you also uncomment the `debug` line in `/etc/nvidia-container-runtime/config.toml` and paste the output of the log file?

Thanks!

**Comment by archenroot** [comment]
@angryvincent @RenaudWasTaken - thx both for response, will look at that during next week

**Comment by archenroot** [comment]
Still busy with other stuff....

**Comment by lexxxel** [comment]
```
I0709 15:22:47.338887 32 nvc.c:281] initializing library context (version=1.0.2, build=773b1954446b73921ce16919248c764ff62d29ad)
I0709 15:22:47.338927 32 nvc.c:255] using root /
I0709 15:22:47.338932 32 nvc.c:256] using ldcache /etc/ld.so.cache
I0709 15:22:47.338934 32 nvc.c:257] using unprivileged user 65534:65534
I0709 15:22:47.340978 33 nvc.c:191] loading kernel module nvidia
I0709 15:22:47.341118 33 nvc.c:203] loading kernel module nvidia_uvm
I0709 15:22:47.341211 33 nvc.c:211] loading kernel module nvidia_modeset
I0709 15:22:47.341428 34 driver.c:133] starting driver service
I0709 15:22:47.343330 32 driver.c:233] driver service terminated with signal 15
nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected
```

I wrote my own ebuilds to [here](https://git.lexxxel.de/linux/lexxxel/tree/master/app-emulation). I build everything from src but still didn't got it working ...

Any ideas?

**Comment by lexxxel** [comment]
.... fixed it after asking ...xD
the config.toml was configured incorrect for gentoo

```
disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
#root = "/run/nvidia/driver"
#path = "/usr/bin/nvidia-container-cli"
environment = []
debug = "/var/log/nvidia-container-runtime-hook.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = true
#no-cgroups = false
user = "root:video"
#ldconfig = "@/sbin/ldconfig.real"
```

**Comment by RenaudWasTaken** [comment]
Thanks for helping with this @lexxxel !

**Comment by gronastech** [comment]
https://github.com/gronastech/nvidia-docker-overlay

**Comment by vowstar** [comment]
layman -a vowstar
emerge -av nvidia-container-toolkit

**Comment by lexxxel** [comment]
Without any link, useable without laymen, this does not really help.
Maybe you could add a link to the underlying repo?

**Comment by vowstar** [comment]
> Without any link, useable without laymen, this does not really help.
> Maybe you could add a link to the underlying repo?

https://github.com/vowstar/vowstar-overlay/blob/master/app-emulation/nvidia-container-toolkit/nvidia-container-toolkit-1.1.1.ebuild

https://forums.gentoo.org/viewtopic-t-1114420-start-0.html
