### ISSUE TITLE
Slackware Support / Packages / Install instructions

### ISSUE THREAD

**Issue by Aterfax** [NVIDIA/libnvidia-container#46]
I am unfamiliar with the build system for slack and no packages are available.

Anyone lend a hand / can we get some packages?

**Comment by RenaudWasTaken** [comment]
Hello!

It's unlikely we endup supporting slackware. We try to follow the CUDA support matrix closely.
Closing for now but would be happy to reopen if there are enough users.

**Comment by ich777** [comment]
I'm also interested, I've tried to build it from the source but now I'm stuck, allready opened a issue:
https://github.com/NVIDIA/nvidia-container-runtime/issues/101#issue-622703550

All files are visible in the container but they all show up with zero filesize.

**Comment by klueska** [comment]
We were able to work through the issues on this thread: https://github.com/NVIDIA/nvidia-container-runtime/issues/101#issue-622703550
