### ISSUE TITLE
Error: "driver service terminated with signal 15"

### ISSUE THREAD

**Issue by nlgranger** [NVIDIA/libnvidia-container#48]
System:
- Archlinux
- Linux: 4.19.26-1-lts
- Nvidia: 418.43
- Cuda: 10.0.130
- [dmesg.txt](https://github.com/NVIDIA/libnvidia-container/files/2938233/dmesg.txt)

Built steps:
```
make WITH_TIRPC=yes prefix=/usr/local
make install
```
NOTE: Build failed unless the attached patched was applied to fix the Makefile
[fix_flags.patch.txt](https://github.com/NVIDIA/libnvidia-container/files/2938232/fix_flags.patch.txt)

Failing command command:
```
$ nvidia-container-cli --debug=log.txt info
nvidia-container-cli: initialization error: cuda error: unknown error
```
Content of log.txt:
```

-- WARNING, the following logs are for debugging purposes only --

I0306 20:39:40.826306 23023 nvc.c:281] initializing library context (version=1.0.1, build=fe20a8e4a17a63df8116f39795173a461325fb3d)
I0306 20:39:40.826369 23023 nvc.c:255] using root /
I0306 20:39:40.826378 23023 nvc.c:256] using ldcache /etc/ld.so.cache
I0306 20:39:40.826385 23023 nvc.c:257] using unprivileged user 1000:1000
I0306 20:39:40.826624 23024 driver.c:133] starting driver service
I0306 20:39:40.874145 23023 driver.c:233] driver service terminated with signal 15
```

**Comment by RenaudWasTaken** [comment]
Seems very likely that your driver installation is broken.

Are you able to run cuda samples outside a container? 
Also possible your driver isn't loaded, can you run the CLI command with sudo just one time?

**Comment by nlgranger** [comment]
I did run it as root, it returns the same error.
Cuda samples such as deviceQuery run fine, nvidia-smi runs fine.

**Comment by nlgranger** [comment]
Is there any way I can get more details about what is failing? The debug message is a bit terse.

**Comment by nlgranger** [comment]
It seems to be working now. AFAIK, the only thing I changed was to install cuda *before* compiling the library.
Not having cuda doesn't raise any error during the compilation though.

**Comment by RenaudWasTaken** [comment]
My feeling is that your driver isn't properly loaded. Do you have the kernel modules loaded, or the devices available in /dev/nvidia ?

**Comment by nlgranger** [comment]
The kernel modules are loaded, persistence daemon is running, both devices appear (/dev/nvidia0, /dev/nvidia1).

**Comment by nlgranger** [comment]
Ok, when compiling in debug mode I get

`nvidia-container-cli: initialization error: cuda error: out of memory`

For your information, here is the output of the command with strace.

[strace.txt](https://github.com/NVIDIA/libnvidia-container/files/2953997/strace.txt)

**Comment by klueska** [comment]
Is this still an issue you are having or is it OK to close this issue now?

**Comment by nlgranger** [comment]
I don't  have the environment to reproduce the test anymore. I can reopen later if someone reports the same issue in the future.

**Comment by Davidrjx** [comment]
same error after tainting a GPU card with fan error in k8s

**Comment by nlgranger** [comment]
I suggest you open a new issue because the code base and environment must have changed a lot since this issue was opened.
