### ISSUE TITLE
RPM repository unavailable

### ISSUE THREAD

**Issue by frankthetank** [NVIDIA/libnvidia-container#5]
This is a placeholder for the same issue that is occurring at NVIDIA/nvidia-container-runtime#4 replacing the URLS as:

https://nvidia.github.io/libnvidia-container/centos7/x86_64
http://nvidia.github.io/libnvidia-container/centos7/x86_64

**Comment by frankthetank** [comment]
OK - so repository browsing is not enabled.  That's not a problem 

After some more troubleshooting I think I have found where the issue is and why it was displaying the way it did.

Nutshell: I am using Artifactory to proxy YUM repositories into my lab.  I've got the three NVIDIA repositories required for nvidia-docker added individually and then aggregated into a virtual repository.  The issue is that the .xz files available from this project are corrupt or invalid.  When this happens during Artifactory's aggregation work it is failing the entire return and telling me that the objects cannot be found.

I can reproduce this by directly downloading a file and trying to extract it:
```
curl -O https://nvidia.github.io/libnvidia-container/centos7/x86_64/repodata/e71656904242b818e3e0083f0bc838d1a542180a6698ed6a06525250ccb084c791bb65ba798a824e7da549507ecf6e53f3c3d8c6a440e9bf8a4b3513fdd2fb41-filelists.xml.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9340  100  9340    0     0  30983      0 --:--:-- --:--:-- --:--:-- 31029

xz --decompress e71656904242b818e3e0083f0bc838d1a542180a6698ed6a06525250ccb084c791bb65ba798a824e7da549507ecf6e53f3c3d8c6a440e9bf8a4b3513fdd2fb41-filelists.xml.xz 
xz: e71656904242b818e3e0083f0bc838d1a542180a6698ed6a06525250ccb084c791bb65ba798a824e7da549507ecf6e53f3c3d8c6a440e9bf8a4b3513fdd2fb41-filelists.xml.xz: File format not recognized
```

Thoughts?

**Comment by frankthetank** [comment]
FYSA - the Artifactory log appears to be dropping a similar error message to what I've added above:
```
repodata/9033186568698a6554981b26ad3cb6d6defc449aca0d822897118741b8b7c50dba43fbd24c9058087fda9c7265cd58a6278d1ffa49e1ae34a6c262668ef1713a-primary.xml.xz: Given input stream could not be recognized as an archive stream
```

**Comment by flx42** [comment]
Not sure where these hashes are coming from, they were never valid objects AFAIK.

**Comment by flx42** [comment]
Previous commit:
https://github.com/NVIDIA/libnvidia-container/tree/258f33d1c93eb892feee4ede680ea05f9392e9f8/centos7/x86_64/repodata

Current commit:
https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/centos7/x86_64/repodata

**Comment by frankthetank** [comment]
Sorry - dealing with all three repositories.  That hash is from nvidia-docker.  My bad.

**Comment by flx42** [comment]
Yeah all these repositories can be a bit confusing :).
Closing this one, let me know if there is a problem with the nvidia-docker repo.
