### ISSUE TITLE
I can't update libnvidia-container

### ISSUE THREAD

**Issue by EricYangsw** [NVIDIA/libnvidia-container#51]
W: Failed to fetch https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64/InRelease  Could not resolve host: nvidia.github.io

**Comment by RenaudWasTaken** [comment]
Hi!

This is in all likelihood a network issue on your side. 
I would suggest you look into making `wget https://github.com` first.

Feel free to open a new issue if you have other problems!
