### ISSUE TITLE
Error: ubuntu18.04/arm64  Release Not Found

### ISSUE THREAD

**Issue by releasethekragle** [NVIDIA/libnvidia-container#52]
Running Ubuntu 18.04 LTS

Get the following error when I run "sudo apt-get update"

Err:13 https://nvidia.github.io/libnvidia-container/ubuntu18.04/arm64  Release 
  404  Not Found [IP: 185.199.111.153 443]

when will this be released for 18.04 ?

Thank you.

Errors listed attached
[Ubuntu 18.04 LTS Error.pdf](https://github.com/NVIDIA/libnvidia-container/files/3149822/Ubuntu.18.04.LTS.Error.pdf)

**Comment by RenaudWasTaken** [comment]
Same comment as here: https://github.com/NVIDIA/nvidia-container-runtime/issues/58#issuecomment-489815919

We don't support ARM.
