### ISSUE TITLE
Centos distrobution not found

### ISSUE THREAD

**Issue by kikoalbiol** [NVIDIA/libnvidia-container#53]
This issus does not show the reopo correctly for CENTOS based 

It should expect other distribution

**Comment by RenaudWasTaken** [comment]
Hello!

Please follow the configuration as follows:
```
DIST="centos7"
curl -s -L https://nvidia.github.io/libnvidia-container/gpgkey |  sudo apt-key add -
curl -s -L https://nvidia.github.io/libnvidia-container/$DIST/libnvidia-container.list |  sudo tee /etc/apt/sources.list.d/libnvidia-container.list
sudo apt-get update
```

We don't support other versions of centos, if you have a different version you can always try the centos7 packages
