### ISSUE TITLE
Repository configuration for SLES and OpenSUSE

### ISSUE THREAD

**Issue by Hui-Zhi** [NVIDIA/libnvidia-container#54]
Hi,  is this supported on SLES and OpenSUSE? If not, do you have a plan?

**Comment by Hui-Zhi** [comment]
Can anyone give some comments?

**Comment by Hui-Zhi** [comment]
#40

**Comment by Hui-Zhi** [comment]
Related to #40

**Comment by RenaudWasTaken** [comment]
Hello!

This got added a while back :)
