### ISSUE TITLE
nvidia-container-cli fails to enable Vulkan in containers

### ISSUE THREAD

**Issue by foresto** [NVIDIA/libnvidia-container#55]
I'm using lxc with the mount hook that calls nvidia-container-cli, and it works for running nvidia-smi and opengl applications in the container. However, vulkan applications, including vulkaninfo, vkcube, and games, all fail. For example:

> $ vulkaninfo
> Cannot create Vulkan instance.
> /build/vulkan-tools-_xrZWD/vulkan-tools-1.1.101.0+dfsg1/vulkaninfo/vulkaninfo.c:884: failed with VK_ERROR_INCOMPATIBLE_DRIVER

Digging a little deeper with strace, I found that /usr/share/vulkan/icd.d/nvidia_icd.json is missing in the container. When I manually exported it to the container's filesystem, I got a new error:

> $ vulkaninfo
> The NVIDIA driver was unable to open 'libnvidia-glvkspirv.so.430.14'.  This library is required at run time.
> 
> WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
> Cannot create Vulkan instance.
> /build/vulkan-tools-_xrZWD/vulkan-tools-1.1.101.0+dfsg1/vulkaninfo/vulkaninfo.c:884: failed with VK_ERROR_INCOMPATIBLE_DRIVER

Following the trail of errors, I tried manually exporting /usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.430.14 into the container. At that point, vulkan applications started working.

So, it looks like nvidia-container-cli and/or its libraries are failing to expose at least these files to the container:

/usr/share/vulkan/icd.d/nvidia_icd.json
/usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.*
/usr/lib/i386-linux-gnu/libnvidia-glvkspirv.so.*

Can you folks please fix this?

**Comment by RenaudWasTaken** [comment]
Hello!

Vulkan isn't supported in containers yet. One of the reasons is we haven't discussed with someone familiar with Vulkan. 

Ideally I would be interested in having some confirmation that this is the only thing we need to do to enable Vulkan in nvidia containers.

**Comment by foresto** [comment]
Oh? That's surprising, since Vulkan is listed under nvidia-container-runtime's [supported driver capabilities](/NVIDIA/nvidia-container-runtime/#supported-driver-capabilities). Would it not make sense to expose those files now even if they're officially unsupported, since they're part of the same driver package whose other files are already exposed, and since I can confirm that their presence makes things work?

In any case, thanks for the info. I suppose I'll have to continue mounting those three files manually until support is added here.

**Comment by stgraber** [comment]
It'd be great if the common files could at least get added as that's causing issues for our users who use LXD containers to run steam and other games.
(As can be seen in the linked LXD issue)

**Comment by RenaudWasTaken** [comment]
@stgraber we've started working on this and are hoping to enable it in the next few weeks :)
cc @guptaNswati

**Comment by guptaNswati** [comment]
@stgraber thats the goal. Right now I am trying to find all the needed deps across different versions, so that we can make it generic. One of the libs it needs is libnvidia_GLX.so that libnvidia-container already exposes if the graphics option is used but not others. And icd_loader comes from nvidia_utils package that also needs to be added.

**Comment by stgraber** [comment]
Excellent, thanks for working on this!

**Comment by qhaas** [comment]
Getting the same error as the OP with libnvidia-container-tools 1.0.0, in EL7 on ppc64le:
```
$ nvidia-container-cli --version
version: 1.0.0
...
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
$ nvidia-container-cli info
NVRM version:   418.87.00
CUDA version:   10.1
...
```
Looks like 'libnvidia-glvkspirv' isn't being picked up by nvidia-container-cli
```
$ nvidia-container-cli list | grep libnvidia-glvkspirv | wc -l
0
```

**Comment by RenaudWasTaken** [comment]
@stgraber I don't think we wrote on this thread but @guptaNswati created an image a while back:
- https://gitlab.com/nvidia/container-images/vulkan
- https://hub.docker.com/r/nvidia/vulkan

@qhaas PPC packages are outdated and haven't been updated in a while (due to the lack of an actual machine) we are targeting publishing some in the current month.
