### ISSUE TITLE
Optix 6.0 support

### ISSUE THREAD

**Issue by robertsulej** [NVIDIA/libnvidia-container#58]
Since Optix 6.0 a part of its libraries was moved to the GPU driver and became inaccessible in docker. This issue was reported on the [nvidia developers forum](https://devtalk.nvidia.com/default/topic/1050039/optix/optix-6-0-0-inside-nvidia-docker/post/5329213/#5329213) and also reported in the [nvidia-docker issues](https://gitlab.com/nvidia/cuda/issues/40).

I am the next one interested in running Optix in the virtual environment. The advise in the fora above was to open an issue here so here I am. I compiled an image with one of the Optix 6 SDK samples (failing) and the same with Optix 5 (running OK) in case it is useful to demonstrate the problem.

Image is configured to run Optix 6 sample:

`docker run --rm --runtime=nvidia rsulej/optix-docker-test`

You can run exactly the same but with Optix 5 in the interactive mode:

`docker run --rm --runtime=nvidia -it rsulej/optix-docker-test sh`

and inside the container:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/minimalOptixSample/optix5
/minimalOptixSample/optix5/optixDeviceQuery
```

The whole setup is available also in [GitHub](https://github.com/robertsulej/minimalOptixSample).

Help on this would be really appreciated. Thanks!
Robert

**Comment by qhaas** [comment]
Looks like this was addressed in v1.0.4, thanks guys!
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.0.4
