### ISSUE TITLE
Debian8 Support

### ISSUE THREAD

**Issue by JorgeAtSalk** [NVIDIA/libnvidia-container#63]
The following Debian 8 sources now return 

# Unsupported distribution! 

Is Debian 8 no longer supported? The Repo list page says it is: https://nvidia.github.io/nvidia-docker/

Deb 8 Sources from Nvidia's GitHub listing:

deb https://nvidia.github.io/libnvidia-container/debian8/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/debian8/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/debian8/$(ARCH) /

Jorge

**Comment by rajatchopra** [comment]
Yes, this was removed. I take this as a request for it to be brought back. Will update the issue.

**Comment by JorgeAtSalk** [comment]
Yes, it would be greatly appreciated if it could be brought back. I know we need to upgrade to Debian v9 or even v10 and its to be done but just not yet. Users are still finishing up projects and this would aid in that.

Thank you!

**Comment by RenaudWasTaken** [comment]
Hello!

Debian8 isn't supported because docker doesn't support it anymore :)
What that means is that we don't publish new updates, however old packages are still available :)
