### ISSUE TITLE
Feature Request: Create a release for Docker on Nvidia-Jetson (arm64 ubuntu18.04)

### ISSUE THREAD

**Issue by markope** [NVIDIA/libnvidia-container#64]
Previously this has been reported as a bug (see #58 , #52 , #7 ), but as you mentioned it is just not supported by you.

So here is a feature request :-)

**Comment by ilanbiala** [comment]
There was a release yesterday, @RenaudWasTaken does that fix this in any way?

**Comment by RenaudWasTaken** [comment]
Hello!

Because Jetson support is still very early and we had to fork, we don't intend to make a release for that.

As soon as it makes it back in master I'll be making releases.
