### ISSUE TITLE
How to load mount plugins?

### ISSUE THREAD

**Issue by ilanbiala** [NVIDIA/libnvidia-container#65]
The docs have a section on mount plugins and some information about valid mount plugins, but the [loading section](https://github.com/NVIDIA/libnvidia-container/blob/jetson/design/mount_plugins.md#mount-plugin-loading) doesn't actually seem to describe how to load them when building/running an image. Can someone clarify?

**Comment by RenaudWasTaken** [comment]
Hello!

Mount plugins aren't a user facing feature and not expected to be used when building an image.
Mount plugins are also specific to Jetson and we have no plan to port them anywhere else at the moment (and will likely disappear in the future).

With that said, mount plugins are just a file on the host that describes what needs to be mounted in the container.
