### ISSUE TITLE
Relicensing to Apache2+DCO

### ISSUE THREAD

**Issue by RenaudWasTaken** [NVIDIA/libnvidia-container#66]
Hello everyone!

We'll be relicensing this repository from BSD3 to an Apache2 License.
This will allow us to move away from the CLA model to a DCO model.

As part of that process, we have two options:
1. Ask our contributors to approve that change
2. Rollback that change

We also think that it's good practice to ask our contributors before we rollback their changes!

So far I've noticed that the only commit that is from an external contributor is the following:
- https://github.com/NVIDIA/libnvidia-container/commit/391c4b636800bdb8bd221fab33e200bbed16fdf9#diff-7bc97225ec599bcfbe5a8008f46a8559

@stgraber are you fine with us relicensing this repository?
Thanks!

**Comment by stgraber** [comment]
Yep, absolutely fine with the relicensing.

**Comment by RenaudWasTaken** [comment]
Closing as this is done. Thanks @stgraber !
