### ISSUE TITLE
 Couldn't find libnvidia-ml.so library 

### ISSUE THREAD

**Issue by comassky** [NVIDIA/libnvidia-container#67]
Hi :)

OS : Debian 10
libnvidia-container 1 1.0.4-1 
Nvidia 430.40
Docker 19.03.1

When a launch docker container with nvidia-runtime-container, nvidia-smi command inside the container says : 

> 
> NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
> Please also try adding directory that contains libnvidia-ml.so to your system PATH.

I must launch ldconfig within the container and it fix the problem.

But i thinck launch this command should not be necessary 👍

**Comment by comassky** [comment]
![image](https://user-images.githubusercontent.com/48486646/63709709-b790fe00-c837-11e9-8f1a-c7c5089a2437.png)

**Comment by RenaudWasTaken** [comment]
Hello!

Please open your issue in the nvidia-docker2 repo and fill the issue template!
https://github.com/NVIDIA/nvidia-docker
