### ISSUE TITLE
VK_NV_ray_tracing not supported in Vulkan container

### ISSUE THREAD

**Issue by JasonGreenNV** [NVIDIA/libnvidia-container#68]
When running libnvidia-container 1.0.5 via Docker, I'm able to get a Vulkan context just fine. However, it appears that VK_NV_ray_tracing is not advertised inside the container. I've tried with both 430.26 and 435.21 drivers. The extension is advertised when running outside of docker, but inside, it does not appear.

[nvidia-bug-report.log.gz](https://github.com/NVIDIA/libnvidia-container/files/3627769/nvidia-bug-report.log.gz)

**Comment by JasonGreenNV** [comment]
Here are the results of _vulkaninfo_ both inside and outside of Docker:

- [out_docker.txt](https://github.com/NVIDIA/libnvidia-container/files/3627787/out_docker.txt)
- [in_docker.txt](https://github.com/NVIDIA/libnvidia-container/files/3627788/in_docker.txt)

**Comment by JasonGreenNV** [comment]
Also, I found a workaround to get this going. I had to add this to the `docker run` command:
`-v /usr/lib/x86_64-linux-gnu/libnvidia-cbl.so.435.21:/usr/lib/x86_64-linux-gnu/libnvidia-cbl.so.435.21`. Looks like that lib isn't getting mapped automatically?

**Comment by RenaudWasTaken** [comment]
cc @guptaNswati

**Comment by guptaNswati** [comment]
Done https://github.com/NVIDIA/libnvidia-container/commit/8d90918a6792d0f7de609fca6a0d38ab79dc3d94
