### ISSUE TITLE
LICENSE mismatch

### ISSUE THREAD

**Issue by paroque28** [NVIDIA/libnvidia-container#74]
There are four different licenses in the repository:
- BSD
- APACHE 2
- GPL 3
- Nvidia commercial

**Comment by RenaudWasTaken** [comment]
Hello!

Thanks for opening this issue, I'll be taking a stab at fixing this, since we shouldn't be BSD anymore.
Though I'll be asking our legal department what license should the nvml.h be as I'm not certain how the relicensing impacts that specific file.

GPL is only in the context of building using the system's libelf which is the case on PPC.

**Comment by jordimassaguerpla** [comment]
Hi,
I also noticed this in the RPM spec file.

So the spec file for the RPM states "License: BSD" https://github.com/NVIDIA/libnvidia-container/blob/master/pkg/rpm/SPECS/libnvidia-container.spec#L2, while the project is licensed under the apache 2 https://github.com/NVIDIA/libnvidia-container/blob/master/LICENSE, elftoolchain is bsd (https://github.com/elftoolchain/elftoolchain#copyright-and-license)and nvidia modprobe is GPL https://github.com/NVIDIA/nvidia-modprobe/blob/master/COPYING

Which should be the RPM license?

thanks

**Comment by Klaven** [comment]
Is there anything I can do to help resolve this issue?

**Comment by dcermak** [comment]
To make this more complicated, the list from @paroque28 is not exhaustive. A scan via fossa found the following licenses:
- GPL-3.0-ONLY (`COPYING`)
- LGPL-3.0-ONLY (`COPYING.LESSER`)
- LGPL-3.0-OR-LATER (`src/elftool.[c,h]`, `NOTICE`)
- BSD-3-CLAUSE (the spec file)
- APACHE-2.0 (declared license, `LICENSE`, `mk/docker.mk`)

To me it looks like putting LGPL-3.0-ONLY into `COPYING.LESSER` is an oversight, as it is explicitly noted that it applies when this library is linked against libelf.

Unfortunately I am afraid that this is all that we can do, the rest of the licensing is something that @RenaudWasTaken and NVIDIA must fix.
