### ISSUE TITLE
Put opensuse-leap15.1 on the "List of supported distributions"

### ISSUE THREAD

**Issue by Hui-Zhi** [NVIDIA/libnvidia-container#78]
opensuse-leap15.1 is already supported in the code but has not updated on the "List of supported distributions", also has no repo and guide for it.

**Comment by klueska** [comment]
I am in the process of updating the readme to list the support matrix for this library. What exactly do you mean by "it has no repo and guide for it"? I want to make sure I include your requests accurately in the update.

**Comment by dfaure-kdab** [comment]
One issue is that "https://nvidia.github.io/libnvidia-container/opensuse-leap15.1/x86_64/" says "Unsupported distribution"

**Comment by Hui-Zhi** [comment]
@RenaudWasTaken would you mind take a look at this "Unsupported distribution"? And I think **SLE15-SP1-x86_64** should be also on the list here: https://nvidia.github.io/libnvidia-container/ since we have a PR for it.

PR: [Add SLE15-SP1-x86-64 support](https://github.com/NVIDIA/libnvidia-container/pull/79)

**Comment by nvjmayo** [comment]
looks like 15.1 is on the list today.

**Comment by dfaure-kdab** [comment]
https://nvidia.github.io/libnvidia-container/opensuse-leap15.1/x86_64/ still says "Unsupported distribution"

Same for 15.2 (https://nvidia.github.io/libnvidia-container/opensuse-leap15.2/x86_64/)
