### ISSUE TITLE
Offline installers

### ISSUE THREAD

**Issue by pulberg** [NVIDIA/libnvidia-container#82]
I work in a hyper secure environment, we don't have internet access from servers, i'm trying to install 
`nvidia-container-toolkit_1.0.5-1_amd64.deb`
and I get a dep error for `libnvidia-container-tools`.  I can't use the `make` options due to limitations on the servers themselves, I need to be able to download .deb files for my environment, do these exist?

**Comment by klueska** [comment]
You should be able to find all the packages you need from the `gh_pages` branches of the following projects:
`libnvidia-container`: https://github.com/NVIDIA/libnvidia-container/tree/gh-pages
`nvidia-container-runtime`: https://github.com/NVIDIA/nvidia-container-runtime/tree/gh-pages
`nvidia-docker`:  https://github.com/NVIDIA/nvidia-docker/tree/gh-pages

All of NVIDIA's yum and apt-get repos are hosted from these.

The packages for the `nvidia-container-toolkit` are bundled together in the `nvidia-container-runtime` repo.

**Comment by pulberg** [comment]
@klueska Yes, the installers are in that location (I only know this because of working with Nvidia support for over a month), but that location is not "known" to users nor is it referenced in any documentation regarding how to get the files if you don't have internet access from the location you are installing those files.

**Comment by klueska** [comment]
I'll make a note to improve the documentation around this. Do you have everything you need now, or is something still missing?

**Comment by pulberg** [comment]
@klueska Thanks, I think the effort to update the docs is already underway, here is the account rep I have been working with to get this resolved -
