### ISSUE TITLE
"Unable to locate package nvidia-container-toolkit" on Debian8 (jessie)

### ISSUE THREAD

**Issue by mengzhugithub** [NVIDIA/libnvidia-container#84]
I followed the steps listed here: https://github.com/NVIDIA/nvidia-docker

But encountered:
```
$ sudo apt-get install -y nvidia-container-toolkit
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nvidia-container-toolkit
```

```
$ cat  /etc/apt/sources.list.d/nvidia-docker.list
deb https://nvidia.github.io/libnvidia-container/debian8/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/debian8/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/debian8/$(ARCH) /
```

```
$ cat  /etc/apt/sources.list.d/nvidia-docker.list
....
Hit https://nvidia.github.io  InRelease
Hit https://nvidia.github.io  InRelease
Hit https://nvidia.github.io  InRelease
....
```
From https://nvidia.github.io/libnvidia-container/, Debian 8 on x86_64 should be supported. Can you help me with this? Thanks!

Can you help me with this? Thanks!

**Comment by adamryczkowski** [comment]
The same problem with Ubuntu 18.04. I've guessed that they meant $(arch) instead of $(ARCH) - but even in that case 
```
deb https://nvidia.github.io/libnvidia-container/ubuntu18.04/x86_64 /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/x86_64 /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/x86_64 /
```

it does not work. I wonder, how do people overcome this?

**Comment by klueska** [comment]
Debian 8 is no longer supported for newer version of the packages. The documentation is unfortunately out of date.

The last release of `libnvidia-container` that was supported on Debian 8 was [1.0.5](https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.0.5). Since that time, there have been releases for 1.0.6, 1.0.7, 1.1.0, and 1.1.1 that did not include Debian 8 support.

However, everything should be working for Ubuntu 18.04 with the latest packages. I have not heard of anyone else having issues here. The `$(ARCH)` variable is correct (i.e. capitalized), so it's unclear what your issue might be.

**Comment by nvjmayo** [comment]
Yes Debian 8 is no long supported for newer version. [Support ended June 30, 2020](https://wiki.debian.org/LTS). 

You'll have to follow the guide at https://nvidia.github.io/nvidia-docker/ as there are stable and experimental directories for the newer releases.

The Debian 8 repo is still there (`http://nvidia.github.io/nvidia-docker/debian8/nvidia-docker.list` is live), but it shows different paths than you have put in your comments. No one on the team is testing Debian 8 and I have no confidence that it will continue working now that Debian 8 is out of support.

example:

Debian 10:
```sh
$ curl -sL http://nvidia.github.io/nvidia-docker/debian10/nvidia-docker.list
deb https://nvidia.github.io/libnvidia-container/stable/debian10/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/debian10/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/debian10/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/debian10/$(ARCH) /
```

Ubuntu 18.04:
```sh
$ curl -sL http://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
```

Please re-open if you have any further problems.
