### ISSUE TITLE
v1.0.7, v1.1.0, and v1.1.1 tags are missing

### ISSUE THREAD

**Issue by herb-kuta-lge** [NVIDIA/libnvidia-container#85]
The last one [here](https://github.com/NVIDIA/libnvidia-container/releases) is v1.0.6 but I see  v1.0.7, v1.1.0, and v1.1.1 listed in the [changelog](https://github.com/NVIDIA/libnvidia-container/blob/master/pkg/deb/changelog).

**Comment by klueska** [comment]
Yes, we are aware of the inconsistency. There are also missing tags for some of the other components that make up `nvidia-docker`. We will be updating / tagging these repos appropriately soon.

**Comment by klueska** [comment]
I just added tags and releases for:
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.0.6
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.0.7
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.1.0
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.1.1
